import { z } from "zod";
import { defineOperations } from "./types.ts";
import {
  boardEventPageSchema,
  boardGroupSchema,
  boardMutedUserSchema,
  boardSchema,
  boardTagDataSchema,
  createTopicRequestSchema,
  errorCodeSchema,
  numericIdResponseSchema,
  tagGroupSchema,
  topicSchema,
} from "../schemas/index.ts";

export const boardOperations = defineOperations([
  {
    method: "GET",
    path: "/board/all",
    operationId: "getBoardAll",
    summary: "Get all board groups",
    tags: ["Board"],
    parameters: [],
    responses: {
      "200": {
        description: "Board groups",
        contentType: "application/json",
        schema: z.array(boardGroupSchema),
      },
      default: {
        description: "API 错误码",
        contentType: "application/json",
        schema: errorCodeSchema,
      },
    },
    auth: "anonymous",
    risk: "read-only",
    verificationStatus: "verified-anonymous",
    sources: ["legacy-openapi", "live-probe"],
  },
  {
    method: "GET",
    path: "/board/",
    operationId: "getBoard",
    summary: "Get boards by repeated id query",
    tags: ["Board"],
    parameters: [
      { name: "id", in: "query", required: true, schema: z.array(z.number()), probeValue: 758 },
    ],
    responses: {
      "200": {
        description: "Board list",
        contentType: "application/json",
        schema: z.array(boardSchema),
      },
      default: {
        description: "API 错误码",
        contentType: "application/json",
        schema: errorCodeSchema,
      },
    },
    auth: "anonymous",
    risk: "read-only",
    verificationStatus: "verified-anonymous",
    sources: ["legacy-openapi", "live-probe"],
  },
  {
    method: "GET",
    path: "/board/search",
    operationId: "getBoardSearch",
    summary: "Search boards",
    tags: ["Board"],
    parameters: [
      { name: "keyword", in: "query", required: true, schema: z.string(), probeValue: "测试" },
    ],
    responses: {
      "200": {
        description: "Matching boards",
        contentType: "application/json",
        schema: z.array(boardSchema),
      },
      default: {
        description: "API 错误码",
        contentType: "application/json",
        schema: errorCodeSchema,
      },
    },
    auth: "anonymous",
    risk: "read-only",
    verificationStatus: "verified-anonymous",
    sources: ["legacy-openapi", "live-probe"],
  },
  {
    method: "GET",
    path: "/board/{boardId}",
    operationId: "getBoardBoardId",
    summary: "Get board details",
    tags: ["Board"],
    parameters: [
      { name: "boardId", in: "path", required: true, schema: z.number(), probeValue: 758 },
    ],
    responses: {
      "200": { description: "Board details", contentType: "application/json", schema: boardSchema },
      default: {
        description: "API 错误码",
        contentType: "application/json",
        schema: errorCodeSchema,
      },
    },
    auth: "anonymous",
    risk: "read-only",
    verificationStatus: "verified-anonymous",
    sources: ["legacy-openapi", "live-probe"],
  },
  {
    method: "GET",
    path: "/board/{boardId}/topic",
    operationId: "getBoardBoardIdTopic",
    summary: "Get topics in a board",
    tags: ["Board", "Topic"],
    parameters: [
      { name: "boardId", in: "path", required: true, schema: z.number(), probeValue: 758 },
      { name: "from", in: "query", required: true, schema: z.number(), probeValue: 0 },
      { name: "size", in: "query", required: true, schema: z.number(), probeValue: 2 },
    ],
    responses: {
      "200": {
        description: "Topics",
        contentType: "application/json",
        schema: z.array(topicSchema),
      },
      default: {
        description: "API 错误码",
        contentType: "application/json",
        schema: errorCodeSchema,
      },
    },
    auth: "required",
    risk: "read-only",
    verificationStatus: "verified-authenticated",
    sources: ["legacy-openapi", "live-probe"],
  },
  {
    method: "POST",
    path: "/board/{boardId}/topic",
    operationId: "postBoardBoardIdTopic",
    summary: "Create topic in a board",
    tags: ["Board", "Topic"],
    parameters: [
      { name: "boardId", in: "path", required: true, schema: z.number(), probeValue: 758 },
    ],
    requestBody: {
      required: true,
      contentType: "application/json",
      schema: createTopicRequestSchema,
    },
    responses: {
      "200": {
        description: "新主题 ID",
        contentType: "application/json",
        schema: numericIdResponseSchema,
      },
      default: {
        description: "API 错误码",
        contentType: "application/json",
        schema: errorCodeSchema,
      },
    },
    auth: "required",
    risk: "write",
    verificationStatus: "verified-write",
    sources: ["legacy-openapi", "live-probe"],
  },
  {
    method: "GET",
    path: "/board/{boardId}/tag",
    operationId: "getBoardBoardIdTag",
    summary: "Get board tags",
    tags: ["Board"],
    parameters: [
      { name: "boardId", in: "path", required: true, schema: z.number(), probeValue: 758 },
    ],
    responses: {
      "200": {
        description: "Board tag groups",
        contentType: "application/json",
        schema: z.array(tagGroupSchema),
      },
      default: {
        description: "API 错误码",
        contentType: "application/json",
        schema: errorCodeSchema,
      },
    },
    auth: "anonymous",
    risk: "read-only",
    verificationStatus: "verified-anonymous",
    sources: ["legacy-openapi", "live-probe"],
  },
  {
    method: "GET",
    path: "/board/{boardId}/tag-v2",
    operationId: "getBoardBoardIdTagV2",
    summary: "Get board tags v2",
    tags: ["Board"],
    parameters: [
      { name: "boardId", in: "path", required: true, schema: z.number(), probeValue: 758 },
    ],
    responses: {
      "200": {
        description: "Board tag data",
        contentType: "application/json",
        schema: boardTagDataSchema,
      },
      default: {
        description: "API 错误码",
        contentType: "application/json",
        schema: errorCodeSchema,
      },
    },
    auth: "anonymous",
    risk: "read-only",
    verificationStatus: "verified-anonymous",
    sources: ["legacy-openapi", "live-probe"],
    description: "Exact schema is not clear from frontend source.",
  },
  {
    method: "GET",
    path: "/board/{boardId}/events",
    operationId: "getBoardBoardIdEvents",
    summary: "Get board event records",
    tags: ["Board", "Moderation"],
    parameters: [
      { name: "boardId", in: "path", required: true, schema: z.number(), probeValue: 758 },
      { name: "from", in: "query", required: true, schema: z.number(), probeValue: 0 },
      { name: "size", in: "query", required: true, schema: z.number(), probeValue: 2 },
    ],
    responses: {
      "200": {
        description: "Board events",
        contentType: "application/json",
        schema: boardEventPageSchema,
      },
      default: {
        description: "API 错误码",
        contentType: "application/json",
        schema: errorCodeSchema,
      },
    },
    auth: "required",
    risk: "destructive",
    verificationStatus: "verified-authenticated",
    sources: ["legacy-openapi", "live-probe"],
  },
  {
    method: "PUT",
    path: "/board/{boardId}/big-paper",
    operationId: "putBoardBoardIdBigPaper",
    summary: "Update board big-paper announcement",
    tags: ["Board", "Moderation"],
    parameters: [
      { name: "boardId", in: "path", required: true, schema: z.number(), probeValue: 758 },
    ],
    requestBody: {
      required: true,
      contentType: "application/json",
      schema: z.object({ content: z.string() }),
    },
    responses: {
      "200": { description: "Success" },
      default: {
        description: "API 错误码",
        contentType: "application/json",
        schema: errorCodeSchema,
      },
    },
    auth: "required",
    risk: "destructive",
    verificationStatus: "unknown",
    sources: ["legacy-openapi", "live-probe"],
  },
  {
    method: "GET",
    path: "/board/{boardId}/stop-post-user",
    operationId: "getBoardBoardIdStopPostUser",
    summary: "Get board muted users",
    tags: ["Board", "Moderation"],
    parameters: [
      { name: "boardId", in: "path", required: true, schema: z.number(), probeValue: 758 },
      { name: "from", in: "query", required: true, schema: z.number(), probeValue: 0 },
      { name: "size", in: "query", required: true, schema: z.number(), probeValue: 2 },
    ],
    responses: {
      "200": {
        description: "Muted user list",
        contentType: "application/json",
        schema: z.array(boardMutedUserSchema),
      },
      default: {
        description: "API 错误码",
        contentType: "application/json",
        schema: errorCodeSchema,
      },
    },
    auth: "required",
    risk: "destructive",
    verificationStatus: "verified-authenticated",
    sources: ["legacy-openapi", "live-probe"],
  },
  {
    method: "DELETE",
    path: "/board/{boardId}/stop-post-user/{userId}",
    operationId: "deleteBoardBoardIdStopPostUserUserId",
    summary: "Cancel board mute for a user",
    tags: ["Board", "Moderation"],
    parameters: [
      { name: "boardId", in: "path", required: true, schema: z.number(), probeValue: 758 },
      { name: "userId", in: "path", required: true, schema: z.number(), probeValue: 1 },
    ],
    responses: {
      "200": { description: "Success" },
      default: {
        description: "API 错误码",
        contentType: "application/json",
        schema: errorCodeSchema,
      },
    },
    auth: "required",
    risk: "destructive",
    verificationStatus: "unknown",
    sources: ["legacy-openapi", "live-probe"],
  },
]);
