import { z } from "zod";
import { defineOperations } from "./types.ts";
import {
  boardEventPageSchema,
  boardGroupSchema,
  boardMutedUserSchema,
  boardSchema,
  boardSummarySchema,
  boardTagDataSchema,
  createTopicRequestSchema,
  errorCodeSchema,
  numericIdResponseSchema,
  tagGroupSchema,
  topicSchema,
} from "../schemas/index.ts";

export const boardOperations = defineOperations([
  {
    method: "GET",
    path: "/board/all",
    operationId: "getBoardAll",
    summary: "获取全部版面分组",
    tags: ["Board"],
    parameters: [],
    responses: {
      "200": {
        description: "成功获取全部版面分组及版面概要",
        contentType: "application/json",
        schema: z.array(boardGroupSchema),
      },
      default: {
        description: "API 错误码",
        contentType: "application/json",
        schema: errorCodeSchema,
      },
    },
    auth: "anonymous",
    risk: "read-only",
    verificationStatus: "verified-anonymous",
    sources: ["legacy-openapi", "live-probe"],
    description: "返回论坛版面导航使用的全部一级分组，以及每个分组下的版面概要。",
  },
  {
    method: "GET",
    path: "/board/",
    operationId: "getBoard",
    summary: "批量获取指定版面",
    tags: ["Board"],
    parameters: [
      {
        name: "id",
        in: "query",
        required: true,
        schema: z.array(z.number()),
        description: "要查询的版面 ID，可重复传入多个 id 参数；重复的 ID 只返回一次。",
        probeValue: 758,
      },
    ],
    responses: {
      "200": {
        description: "成功获取至少一个匹配的版面详情列表",
        contentType: "application/json",
        schema: z.array(boardSchema),
      },
      default: {
        description: "API 错误码",
        contentType: "application/json",
        schema: errorCodeSchema,
      },
    },
    auth: "anonymous",
    risk: "read-only",
    verificationStatus: "verified-anonymous",
    sources: ["legacy-openapi", "live-probe"],
    description:
      "批量查询一个或多个版面，返回值字段与 /board/{boardId} 相同。适合已有多个版面 ID 时一次补齐收藏、主题记录等列表中的版面资料，避免逐个请求。不存在的 ID 会被忽略，全部 ID 均不存在时返回 404；调用方应按 id 关联结果，不应依赖响应顺序。",
  },
  {
    method: "GET",
    path: "/board/search",
    operationId: "getBoardSearch",
    summary: "搜索版面",
    tags: ["Board"],
    parameters: [
      {
        name: "keyword",
        in: "query",
        required: true,
        schema: z.string(),
        description: "在版面名称或简介中搜索的关键词。",
        probeValue: "校园",
      },
    ],
    responses: {
      "200": {
        description: "成功获取名称或简介匹配关键词的版面",
        contentType: "application/json",
        schema: z.array(boardSummarySchema),
      },
      default: {
        description: "API 错误码",
        contentType: "application/json",
        schema: errorCodeSchema,
      },
    },
    auth: "anonymous",
    risk: "read-only",
    verificationStatus: "verified-anonymous",
    sources: ["legacy-openapi", "live-probe"],
    description: "按关键词搜索版面名称和版面简介，返回匹配的版面概要。",
  },
  {
    method: "GET",
    path: "/board/{boardId}",
    operationId: "getBoardBoardId",
    summary: "获取版面详情",
    tags: ["Board"],
    parameters: [
      {
        name: "boardId",
        in: "path",
        required: true,
        schema: z.number(),
        description: "要查询的版面 ID。",
        probeValue: 758,
      },
    ],
    responses: {
      "200": {
        description: "成功获取版面详情",
        contentType: "application/json",
        schema: boardSchema,
      },
      default: {
        description: "API 错误码",
        contentType: "application/json",
        schema: errorCodeSchema,
      },
    },
    auth: "anonymous",
    risk: "read-only",
    verificationStatus: "verified-anonymous",
    sources: ["legacy-openapi", "live-probe"],
    description:
      "查询单个版面并直接返回一个 Board 对象；需要同时查询多个版面时应使用 /board/ 批量接口，两者返回相同的版面字段。本接口包含版面公告、简介、统计、访问限制和当前访问者能力，登录后还会包含是否已关注等用户相关状态。",
  },
  {
    method: "GET",
    path: "/board/{boardId}/topic",
    operationId: "getBoardBoardIdTopic",
    summary: "获取版面主题列表",
    tags: ["Board", "Topic"],
    parameters: [
      {
        name: "boardId",
        in: "path",
        required: true,
        schema: z.number(),
        description: "要查询主题的版面 ID。",
        probeValue: 758,
      },
      {
        name: "from",
        in: "query",
        required: true,
        schema: z.number(),
        description: "主题列表的起始偏移量。",
        probeValue: 0,
      },
      {
        name: "size",
        in: "query",
        required: true,
        schema: z.number(),
        description: "本次请求的主题数量。",
        probeValue: 2,
      },
    ],
    responses: {
      "200": {
        description: "成功获取当前页的版面主题",
        contentType: "application/json",
        schema: z.array(topicSchema),
      },
      default: {
        description: "API 错误码",
        contentType: "application/json",
        schema: errorCodeSchema,
      },
    },
    auth: "required",
    risk: "read-only",
    verificationStatus: "verified-authenticated",
    sources: ["legacy-openapi", "live-probe"],
    description: "按偏移量分页返回指定版面的普通主题列表；置顶主题由独立接口提供。需要登录。",
  },
  {
    method: "POST",
    path: "/board/{boardId}/topic",
    operationId: "postBoardBoardIdTopic",
    summary: "创建版面主题",
    tags: ["Board", "Topic"],
    parameters: [
      {
        name: "boardId",
        in: "path",
        required: true,
        schema: z.number(),
        description: "要发布主题的版面 ID。",
        probeValue: 758,
      },
    ],
    requestBody: {
      required: true,
      contentType: "application/json",
      schema: createTopicRequestSchema,
    },
    responses: {
      "200": {
        description: "主题创建成功，返回新主题 ID",
        contentType: "application/json",
        schema: numericIdResponseSchema,
      },
      default: {
        description: "API 错误码",
        contentType: "application/json",
        schema: errorCodeSchema,
      },
    },
    auth: "required",
    risk: "write",
    verificationStatus: "verified-write",
    sources: ["legacy-openapi", "live-probe"],
    description:
      "在指定版面创建普通、校园活动、学术通知或投票主题。需要登录，并受到版面发帖、匿名和主题类型权限限制。",
  },
  {
    method: "GET",
    path: "/board/{boardId}/tag",
    operationId: "getBoardBoardIdTag",
    summary: "获取版面分层标签",
    tags: ["Board"],
    parameters: [
      {
        name: "boardId",
        in: "path",
        required: true,
        schema: z.number(),
        description: "要查询标签的版面 ID。",
        probeValue: 459,
      },
    ],
    responses: {
      "200": {
        description: "成功获取按层级拆分的版面标签组",
        contentType: "application/json",
        schema: z.array(tagGroupSchema),
      },
      default: {
        description: "API 错误码",
        contentType: "application/json",
        schema: errorCodeSchema,
      },
    },
    auth: "anonymous",
    risk: "read-only",
    verificationStatus: "verified-anonymous",
    sources: ["legacy-openapi", "live-probe"],
    description: "返回版面可用于主题分类和筛选的标签，并按第一层、第二层分别分组。",
  },
  {
    method: "GET",
    path: "/board/{boardId}/tag-v2",
    operationId: "getBoardBoardIdTagV2",
    summary: "获取版面树状标签",
    tags: ["Board"],
    parameters: [
      {
        name: "boardId",
        in: "path",
        required: true,
        schema: z.number(),
        description: "要查询标签树的版面 ID。",
        probeValue: 459,
      },
    ],
    responses: {
      "200": {
        description: "成功获取版面标签层数和标签树",
        contentType: "application/json",
        schema: boardTagDataSchema,
      },
      default: {
        description: "API 错误码",
        contentType: "application/json",
        schema: errorCodeSchema,
      },
    },
    auth: "anonymous",
    risk: "read-only",
    verificationStatus: "verified-anonymous",
    sources: ["legacy-openapi", "live-probe"],
    description:
      "以树状结构返回版面标签。layers 为 0、1 或 2，顶层标签通过 subTags 包含下一层标签。",
  },
  {
    method: "GET",
    path: "/board/{boardId}/events",
    operationId: "getBoardBoardIdEvents",
    summary: "获取版面管理记录",
    tags: ["Board", "Moderation"],
    parameters: [
      {
        name: "boardId",
        in: "path",
        required: true,
        schema: z.number(),
        description: "要查询管理记录的版面 ID。",
        probeValue: 758,
      },
      {
        name: "from",
        in: "query",
        required: true,
        schema: z.number(),
        description: "管理记录的起始偏移量。",
        probeValue: 0,
      },
      {
        name: "size",
        in: "query",
        required: true,
        schema: z.number(),
        description: "本次请求的管理记录数量。",
        probeValue: 2,
      },
    ],
    responses: {
      "200": {
        description: "成功获取版面管理记录分页结果",
        contentType: "application/json",
        schema: boardEventPageSchema,
      },
      default: {
        description: "API 错误码",
        contentType: "application/json",
        schema: errorCodeSchema,
      },
    },
    auth: "required",
    risk: "read-only",
    verificationStatus: "verified-authenticated",
    sources: ["legacy-openapi", "live-probe"],
    description: "分页返回版面内的管理操作记录，用于版务记录页面。需要登录。",
  },
  {
    method: "PUT",
    path: "/board/{boardId}/big-paper",
    operationId: "putBoardBoardIdBigPaper",
    summary: "更新版面大字报",
    tags: ["Board", "Moderation"],
    parameters: [
      {
        name: "boardId",
        in: "path",
        required: true,
        schema: z.number(),
        description: "要更新大字报的版面 ID。",
        probeValue: 758,
      },
    ],
    requestBody: {
      required: true,
      contentType: "application/json",
      schema: z.object({
        content: z.string().meta({ description: "新的版面大字报内容，使用 CC98 UBB 格式。" }),
      }),
    },
    responses: {
      "200": { description: "版面大字报更新成功" },
      default: {
        description: "API 错误码",
        contentType: "application/json",
        schema: errorCodeSchema,
      },
    },
    auth: "required",
    risk: "destructive",
    verificationStatus: "unknown",
    sources: ["legacy-openapi", "live-probe"],
    description: "更新版面页展示的大字报内容。需要登录和相应的版面管理权限。",
  },
  {
    method: "GET",
    path: "/board/{boardId}/stop-post-user",
    operationId: "getBoardBoardIdStopPostUser",
    summary: "获取版面禁言用户",
    tags: ["Board", "Moderation"],
    parameters: [
      {
        name: "boardId",
        in: "path",
        required: true,
        schema: z.number(),
        description: "要查询禁言用户的版面 ID。",
        probeValue: 758,
      },
      {
        name: "from",
        in: "query",
        required: true,
        schema: z.number(),
        description: "禁言记录的起始偏移量。",
        probeValue: 0,
      },
      {
        name: "size",
        in: "query",
        required: true,
        schema: z.number(),
        description: "本次请求的禁言记录数量。",
        probeValue: 2,
      },
    ],
    responses: {
      "200": {
        description: "成功获取版面禁言用户列表",
        contentType: "application/json",
        schema: z.array(boardMutedUserSchema),
      },
      default: {
        description: "API 错误码",
        contentType: "application/json",
        schema: errorCodeSchema,
      },
    },
    auth: "required",
    risk: "read-only",
    verificationStatus: "verified-authenticated",
    sources: ["legacy-openapi", "live-probe"],
    description: "分页返回指定版面的禁言用户、禁言期限和操作人。需要登录。",
  },
  {
    method: "DELETE",
    path: "/board/{boardId}/stop-post-user/{userId}",
    operationId: "deleteBoardBoardIdStopPostUserUserId",
    summary: "解除用户版面禁言",
    tags: ["Board", "Moderation"],
    parameters: [
      {
        name: "boardId",
        in: "path",
        required: true,
        schema: z.number(),
        description: "要解除禁言的版面 ID。",
        probeValue: 758,
      },
      {
        name: "userId",
        in: "path",
        required: true,
        schema: z.number(),
        description: "要解除版面禁言的用户 ID。",
        probeValue: 1,
      },
    ],
    responses: {
      "200": { description: "用户的版面禁言已解除" },
      default: {
        description: "API 错误码",
        contentType: "application/json",
        schema: errorCodeSchema,
      },
    },
    auth: "required",
    risk: "destructive",
    verificationStatus: "unknown",
    sources: ["legacy-openapi", "live-probe"],
    description: "解除指定用户在该版面的禁言状态。需要登录和相应的版面管理权限。",
  },
]);
