import { z } from "zod";
import { defineOperations } from "./types.ts";
import {
  displayTitleSchema,
  errorCodeSchema,
  globalConfigSchema,
  indexSchema,
  indexColumnSchema,
  serverTimeResponseSchema,
  tagSchema,
} from "../schemas/index.ts";

export const configOperations = defineOperations([
  {
    method: "GET",
    path: "/config/global",
    operationId: "getConfigGlobal",
    summary: "获取论坛全局配置",
    tags: ["Config"],
    parameters: [],
    responses: {
      "200": {
        description: "成功获取论坛全局运行配置与统计信息",
        contentType: "application/json",
        schema: globalConfigSchema,
      },
      default: {
        description: "API 错误码",
        contentType: "application/json",
        schema: errorCodeSchema,
      },
    },
    auth: "anonymous",
    risk: "read-only",
    verificationStatus: "verified-anonymous",
    sources: ["legacy-openapi", "live-probe"],
    description:
      "返回论坛运行状态、全站统计、公告、签到和生日活动等全局配置。接口可匿名访问；旧项目的部分调用会携带 Authorization，但响应不依赖登录态。后端可能省略部分字段或返回额外字段。",
  },
  {
    method: "PUT",
    path: "/config/global/announcement",
    operationId: "putConfigGlobalAnnouncement",
    summary: "更新全站公告",
    tags: ["Config", "Moderation"],
    parameters: [],
    requestBody: {
      required: true,
      contentType: "application/json",
      schema: z.object({
        announcement: z.string().meta({ description: "新的全站公告内容，使用 CC98 UBB 格式。" }),
      }),
    },
    responses: {
      "200": { description: "公告更新成功；成功响应体尚未验证" },
      default: {
        description: "API 错误码",
        contentType: "application/json",
        schema: errorCodeSchema,
      },
    },
    auth: "required",
    risk: "destructive",
    verificationStatus: "unknown",
    sources: ["legacy-openapi", "live-probe"],
    description:
      "更新 `/config/global` 和首页聚合数据中展示的全站公告。该操作需要站点管理权限；当前仅验证了未授权请求会被拒绝，成功响应尚未验证。",
  },
  {
    method: "GET",
    path: "/config/global/advertisement",
    operationId: "getConfigGlobalAdvertisement",
    summary: "获取首页 Banner",
    tags: ["Config", "Index"],
    parameters: [],
    responses: {
      "200": {
        description: "成功获取当前可展示的首页 Banner 列表",
        contentType: "application/json",
        schema: z.array(indexColumnSchema),
      },
      default: {
        description: "API 错误码",
        contentType: "application/json",
        schema: errorCodeSchema,
      },
    },
    auth: "anonymous",
    risk: "read-only",
    verificationStatus: "verified-anonymous",
    sources: ["legacy-openapi", "live-probe"],
    description:
      "返回面向首页访客展示的 Banner。服务端会根据启用状态、过期时间和访问者登录状态筛选配置项，因此响应通常不包含管理端可见的全部记录。",
  },
  {
    method: "GET",
    path: "/config/global/advertisement/all",
    operationId: "getConfigGlobalAdvertisementAll",
    summary: "获取全部首页 Banner 配置",
    tags: ["Config", "Index", "Moderation"],
    parameters: [],
    responses: {
      "200": {
        description: "成功获取全部首页 Banner 配置；成功响应尚未验证",
        contentType: "application/json",
        schema: z.array(indexColumnSchema),
      },
      default: {
        description: "API 错误码",
        contentType: "application/json",
        schema: errorCodeSchema,
      },
    },
    auth: "required",
    risk: "read-only",
    verificationStatus: "permission-denied",
    sources: ["legacy-openapi", "live-probe"],
    description:
      "供站点管理页面读取全部首页 Banner 配置，包括可能已停用、过期或仅对特定登录状态可见的记录。当前仅验证了普通账号会收到权限拒绝，成功响应结构依据旧项目管理页面推断。",
  },
  {
    method: "GET",
    path: "/config/global/special-offer/all",
    operationId: "getConfigGlobalSpecialOfferAll",
    summary: "获取全部福利优惠配置",
    tags: ["Config", "Index", "Moderation"],
    parameters: [],
    responses: {
      "200": {
        description: "成功获取全部福利优惠配置；成功响应尚未验证",
        contentType: "application/json",
        schema: z.array(indexColumnSchema),
      },
      default: {
        description: "API 错误码",
        contentType: "application/json",
        schema: errorCodeSchema,
      },
    },
    auth: "required",
    risk: "read-only",
    verificationStatus: "permission-denied",
    sources: ["legacy-openapi", "live-probe"],
    description:
      "供站点管理页面读取全部福利优惠配置，包括可能已停用、过期或仅对特定登录状态可见的记录。当前仅验证了普通账号会收到权限拒绝，成功响应结构依据旧项目管理页面推断。",
  },
  {
    method: "GET",
    path: "/config/global/alltag",
    operationId: "getConfigGlobalAlltag",
    summary: "获取全部全局标签",
    tags: ["Config"],
    parameters: [],
    responses: {
      "200": {
        description: "成功获取全局标签 ID 与名称列表",
        contentType: "application/json",
        schema: z.array(tagSchema),
      },
      default: {
        description: "API 错误码",
        contentType: "application/json",
        schema: errorCodeSchema,
      },
    },
    auth: "anonymous",
    risk: "read-only",
    verificationStatus: "verified-anonymous",
    sources: ["legacy-openapi", "live-probe"],
    description:
      "返回主题分类和筛选使用的全局标签字典。旧项目会缓存该列表，并用它在标签 ID 与名称之间进行转换。",
  },
  {
    method: "GET",
    path: "/config/now",
    operationId: "getConfigNow",
    summary: "获取服务器时间",
    tags: ["Config"],
    parameters: [],
    responses: {
      "200": {
        description: "成功获取服务器当前时间和业务状态包装",
        contentType: "application/json",
        schema: serverTimeResponseSchema,
      },
      default: {
        description: "API 错误码",
        contentType: "application/json",
        schema: errorCodeSchema,
      },
    },
    auth: "anonymous",
    risk: "read-only",
    verificationStatus: "verified-anonymous",
    sources: ["legacy-openapi", "live-probe"],
    description:
      "返回论坛服务器当前时间。签到和补签页面使用该时间确定当前日期，避免客户端时钟或时区差异影响月份和日期判断。",
  },
  {
    method: "GET",
    path: "/config/index",
    operationId: "getConfigIndex",
    summary: "Get homepage aggregate data",
    tags: ["Index"],
    parameters: [],
    responses: {
      "200": { description: "Homepage data", contentType: "application/json", schema: indexSchema },
      default: {
        description: "API 错误码",
        contentType: "application/json",
        schema: errorCodeSchema,
      },
    },
    auth: "anonymous",
    risk: "read-only",
    verificationStatus: "verified-anonymous",
    sources: ["legacy-openapi", "live-probe"],
  },
  {
    method: "PUT",
    path: "/config/index/update",
    operationId: "putConfigIndexUpdate",
    summary: "Update or clear homepage cache",
    tags: ["Index", "Moderation"],
    parameters: [],
    responses: {
      "200": { description: "Success" },
      default: {
        description: "API 错误码",
        contentType: "application/json",
        schema: errorCodeSchema,
      },
    },
    auth: "required",
    risk: "destructive",
    verificationStatus: "unknown",
    sources: ["legacy-openapi", "live-probe"],
  },
  {
    method: "GET",
    path: "/index/column/{columnKind}/all",
    operationId: "getIndexColumnColumnKindAll",
    summary: "Get all items in a homepage column",
    tags: ["Index", "Moderation"],
    parameters: [
      {
        name: "columnKind",
        in: "path",
        required: true,
        schema: z.union([
          z.literal("recommandationreading"),
          z.literal("recommandationfunction"),
          z.literal("schoolnews"),
        ]),
        probeValue: "recommandationreading",
      },
    ],
    responses: {
      "200": {
        description: "Column items",
        contentType: "application/json",
        schema: z.array(indexColumnSchema),
      },
      default: {
        description: "API 错误码",
        contentType: "application/json",
        schema: errorCodeSchema,
      },
    },
    auth: "required",
    risk: "read-only",
    verificationStatus: "unknown",
    sources: ["legacy-openapi", "live-probe"],
  },
  {
    method: "POST",
    path: "/index/column/",
    operationId: "postIndexColumn",
    summary: "Create homepage column item",
    tags: ["Index", "Moderation"],
    parameters: [],
    requestBody: { required: true, contentType: "application/json", schema: indexColumnSchema },
    responses: {
      "200": { description: "Success" },
      default: {
        description: "API 错误码",
        contentType: "application/json",
        schema: errorCodeSchema,
      },
    },
    auth: "required",
    risk: "destructive",
    verificationStatus: "unknown",
    sources: ["legacy-openapi", "live-probe"],
  },
  {
    method: "PUT",
    path: "/index/column/{id}",
    operationId: "putIndexColumnId",
    summary: "Update homepage column item",
    tags: ["Index", "Moderation"],
    parameters: [{ name: "id", in: "path", required: true, schema: z.number(), probeValue: 758 }],
    requestBody: { required: true, contentType: "application/json", schema: indexColumnSchema },
    responses: {
      "200": { description: "Success" },
      default: {
        description: "API 错误码",
        contentType: "application/json",
        schema: errorCodeSchema,
      },
    },
    auth: "required",
    risk: "destructive",
    verificationStatus: "unknown",
    sources: ["legacy-openapi", "live-probe"],
  },
  {
    method: "GET",
    path: "/config/global/all-user-title",
    operationId: "getConfigGlobalAllUserTitle",
    summary: "获取全部用户头衔",
    tags: ["Config", "User"],
    parameters: [],
    responses: {
      "200": {
        description: "成功获取全部用户头衔定义",
        contentType: "application/json",
        schema: z.array(displayTitleSchema),
      },
      default: {
        description: "API 错误码",
        contentType: "application/json",
        schema: errorCodeSchema,
      },
    },
    auth: "anonymous",
    risk: "read-only",
    verificationStatus: "verified-anonymous",
    sources: ["legacy-openapi", "live-probe"],
    description:
      "返回用户头衔定义。客户端根据用户资料中的 displayTitleId 和 userTitleIds 展示可选头衔、用户徽章或头像框。",
  },
]);
