import { z } from "zod";
import { defineOperations } from "./types.ts";
import {
  displayTitleSchema,
  errorCodeSchema,
  globalConfigSchema,
  indexSchema,
  indexColumnSchema,
  tagSchema,
} from "../schemas/index.ts";

export const configOperations = defineOperations([
  {
    method: "GET",
    path: "/config/global",
    operationId: "getConfigGlobal",
    summary: "Get global config",
    tags: ["Config"],
    parameters: [],
    responses: {
      "200": {
        description: "Global config",
        contentType: "application/json",
        schema: globalConfigSchema,
      },
      default: {
        description: "API 错误码",
        contentType: "application/json",
        schema: errorCodeSchema,
      },
    },
    auth: "anonymous",
    risk: "read-only",
    verificationStatus: "verified-anonymous",
    sources: ["legacy-openapi", "live-probe"],
    description: "Some frontend call sites send Authorization and some do not.",
  },
  {
    method: "PUT",
    path: "/config/global/announcement",
    operationId: "putConfigGlobalAnnouncement",
    summary: "Update global announcement",
    tags: ["Config", "Moderation"],
    parameters: [],
    requestBody: {
      required: true,
      contentType: "application/json",
      schema: z.object({ announcement: z.string() }),
    },
    responses: {
      "200": { description: "Success" },
      default: {
        description: "API 错误码",
        contentType: "application/json",
        schema: errorCodeSchema,
      },
    },
    auth: "required",
    risk: "destructive",
    verificationStatus: "unknown",
    sources: ["legacy-openapi", "live-probe"],
  },
  {
    method: "GET",
    path: "/config/global/advertisement",
    operationId: "getConfigGlobalAdvertisement",
    summary: "Get homepage advertisements",
    tags: ["Config", "Index"],
    parameters: [],
    responses: {
      "200": {
        description: "Advertisement list",
        contentType: "application/json",
        schema: z.array(indexColumnSchema),
      },
      default: {
        description: "API 错误码",
        contentType: "application/json",
        schema: errorCodeSchema,
      },
    },
    auth: "anonymous",
    risk: "read-only",
    verificationStatus: "verified-anonymous",
    sources: ["legacy-openapi", "live-probe"],
  },
  {
    method: "GET",
    path: "/config/global/advertisement/all",
    operationId: "getConfigGlobalAdvertisementAll",
    summary: "Get all advertisement config items",
    tags: ["Config", "Index", "Moderation"],
    parameters: [],
    responses: {
      "200": {
        description: "Advertisement config list",
        contentType: "application/json",
        schema: z.array(indexColumnSchema),
      },
      default: {
        description: "API 错误码",
        contentType: "application/json",
        schema: errorCodeSchema,
      },
    },
    auth: "required",
    risk: "read-only",
    verificationStatus: "permission-denied",
    sources: ["legacy-openapi", "live-probe"],
  },
  {
    method: "GET",
    path: "/config/global/special-offer/all",
    operationId: "getConfigGlobalSpecialOfferAll",
    summary: "Get all special-offer config items",
    tags: ["Config", "Index", "Moderation"],
    parameters: [],
    responses: {
      "200": {
        description: "Special offer config list",
        contentType: "application/json",
        schema: z.array(indexColumnSchema),
      },
      default: {
        description: "API 错误码",
        contentType: "application/json",
        schema: errorCodeSchema,
      },
    },
    auth: "required",
    risk: "read-only",
    verificationStatus: "permission-denied",
    sources: ["legacy-openapi", "live-probe"],
  },
  {
    method: "GET",
    path: "/config/global/alltag",
    operationId: "getConfigGlobalAlltag",
    summary: "Get all global tags",
    tags: ["Config"],
    parameters: [],
    responses: {
      "200": {
        description: "Tag list",
        contentType: "application/json",
        schema: z.array(tagSchema),
      },
      default: {
        description: "API 错误码",
        contentType: "application/json",
        schema: errorCodeSchema,
      },
    },
    auth: "anonymous",
    risk: "read-only",
    verificationStatus: "verified-anonymous",
    sources: ["legacy-openapi", "live-probe"],
  },
  {
    method: "GET",
    path: "/config/now",
    operationId: "getConfigNow",
    summary: "Get server time",
    tags: ["Config"],
    parameters: [],
    responses: {
      "200": {
        description: "Current server time",
        contentType: "application/json",
        schema: z.object({ data: z.string().optional() }),
      },
      default: {
        description: "API 错误码",
        contentType: "application/json",
        schema: errorCodeSchema,
      },
    },
    auth: "anonymous",
    risk: "read-only",
    verificationStatus: "verified-anonymous",
    sources: ["legacy-openapi", "live-probe"],
  },
  {
    method: "GET",
    path: "/config/index",
    operationId: "getConfigIndex",
    summary: "Get homepage aggregate data",
    tags: ["Index"],
    parameters: [],
    responses: {
      "200": { description: "Homepage data", contentType: "application/json", schema: indexSchema },
      default: {
        description: "API 错误码",
        contentType: "application/json",
        schema: errorCodeSchema,
      },
    },
    auth: "anonymous",
    risk: "read-only",
    verificationStatus: "verified-anonymous",
    sources: ["legacy-openapi", "live-probe"],
  },
  {
    method: "PUT",
    path: "/config/index/update",
    operationId: "putConfigIndexUpdate",
    summary: "Update or clear homepage cache",
    tags: ["Index", "Moderation"],
    parameters: [],
    responses: {
      "200": { description: "Success" },
      default: {
        description: "API 错误码",
        contentType: "application/json",
        schema: errorCodeSchema,
      },
    },
    auth: "required",
    risk: "destructive",
    verificationStatus: "unknown",
    sources: ["legacy-openapi", "live-probe"],
  },
  {
    method: "GET",
    path: "/index/column/{columnKind}/all",
    operationId: "getIndexColumnColumnKindAll",
    summary: "Get all items in a homepage column",
    tags: ["Index", "Moderation"],
    parameters: [
      {
        name: "columnKind",
        in: "path",
        required: true,
        schema: z.union([
          z.literal("recommandationreading"),
          z.literal("recommandationfunction"),
          z.literal("schoolnews"),
        ]),
        probeValue: "recommandationreading",
      },
    ],
    responses: {
      "200": {
        description: "Column items",
        contentType: "application/json",
        schema: z.array(indexColumnSchema),
      },
      default: {
        description: "API 错误码",
        contentType: "application/json",
        schema: errorCodeSchema,
      },
    },
    auth: "required",
    risk: "read-only",
    verificationStatus: "unknown",
    sources: ["legacy-openapi", "live-probe"],
  },
  {
    method: "POST",
    path: "/index/column/",
    operationId: "postIndexColumn",
    summary: "Create homepage column item",
    tags: ["Index", "Moderation"],
    parameters: [],
    requestBody: { required: true, contentType: "application/json", schema: indexColumnSchema },
    responses: {
      "200": { description: "Success" },
      default: {
        description: "API 错误码",
        contentType: "application/json",
        schema: errorCodeSchema,
      },
    },
    auth: "required",
    risk: "destructive",
    verificationStatus: "unknown",
    sources: ["legacy-openapi", "live-probe"],
  },
  {
    method: "PUT",
    path: "/index/column/{id}",
    operationId: "putIndexColumnId",
    summary: "Update homepage column item",
    tags: ["Index", "Moderation"],
    parameters: [{ name: "id", in: "path", required: true, schema: z.number(), probeValue: 758 }],
    requestBody: { required: true, contentType: "application/json", schema: indexColumnSchema },
    responses: {
      "200": { description: "Success" },
      default: {
        description: "API 错误码",
        contentType: "application/json",
        schema: errorCodeSchema,
      },
    },
    auth: "required",
    risk: "destructive",
    verificationStatus: "unknown",
    sources: ["legacy-openapi", "live-probe"],
  },
  {
    method: "GET",
    path: "/config/global/all-user-title",
    operationId: "getConfigGlobalAllUserTitle",
    summary: "Get all user display titles",
    tags: ["Config", "User"],
    parameters: [],
    responses: {
      "200": {
        description: "User display titles",
        contentType: "application/json",
        schema: z.array(displayTitleSchema),
      },
      default: {
        description: "API error code",
        contentType: "application/json",
        schema: errorCodeSchema,
      },
    },
    auth: "anonymous",
    risk: "read-only",
    verificationStatus: "verified-anonymous",
    sources: ["legacy-openapi", "live-probe"],
  },
]);
