import { z } from "zod";
import { defineOperations } from "./types.ts";
import {
  annualReviewSchema,
  annualReviewV2Schema,
  changeUserRequestSchema,
  errorCodeSchema,
  makeUpSigninResultSchema,
  meUserSchema,
  messageCountsSchema,
  pagedFavoriteTopicGroupSchema,
  pagedPostResultSchema,
  pagedTopicResultDataSchema,
  privateMessageSchema,
  recentContactSchema,
  sendMessageRequestSchema,
  signinInfoSchema,
  signinRecordSchema,
  themeSettingSchema,
  topicSchema,
  transferWealthRequestSchema,
} from "../schemas/index.ts";

export const meOperations = defineOperations([
  {
    method: "GET",
    path: "/me",
    operationId: "getMe",
    summary: "Get current user",
    tags: ["Me"],
    parameters: [],
    responses: {
      "200": { description: "Current user", contentType: "application/json", schema: meUserSchema },
      default: {
        description: "API 错误码",
        contentType: "application/json",
        schema: errorCodeSchema,
      },
    },
    auth: "required",
    risk: "account-scoped",
    verificationStatus: "verified-authenticated",
    sources: ["legacy-openapi", "live-probe"],
  },
  {
    method: "PUT",
    path: "/me",
    operationId: "putMe",
    summary: "Update current user profile",
    tags: ["Me"],
    parameters: [],
    requestBody: {
      required: true,
      contentType: "application/json",
      schema: changeUserRequestSchema,
    },
    responses: {
      "200": { description: "Success" },
      default: {
        description: "API 错误码",
        contentType: "application/json",
        schema: errorCodeSchema,
      },
    },
    auth: "required",
    risk: "write",
    verificationStatus: "unknown",
    sources: ["legacy-openapi", "live-probe"],
  },
  {
    method: "PUT",
    path: "/me/portrait",
    operationId: "putMePortrait",
    summary: "Update current user's portrait URL",
    tags: ["Me"],
    parameters: [],
    requestBody: { required: true, contentType: "application/json", schema: z.string() },
    responses: {
      "200": { description: "Success" },
      default: {
        description: "API 错误码",
        contentType: "application/json",
        schema: errorCodeSchema,
      },
    },
    auth: "required",
    risk: "write",
    verificationStatus: "unknown",
    sources: ["legacy-openapi", "live-probe"],
  },
  {
    method: "PUT",
    path: "/me/theme",
    operationId: "putMeTheme",
    summary: "Set current user's theme",
    tags: ["Me"],
    parameters: [{ name: "id", in: "query", required: true, schema: z.number(), probeValue: 758 }],
    responses: {
      "200": { description: "Success" },
      default: {
        description: "API 错误码",
        contentType: "application/json",
        schema: errorCodeSchema,
      },
    },
    auth: "required",
    risk: "write",
    verificationStatus: "unknown",
    sources: ["legacy-openapi", "live-probe"],
  },
  {
    method: "PUT",
    path: "/me/theme-setting",
    operationId: "putMeThemeSetting",
    summary: "Set current user's theme switching rules",
    tags: ["Me"],
    parameters: [],
    requestBody: { required: true, contentType: "application/json", schema: themeSettingSchema },
    responses: {
      "200": { description: "Success" },
      default: {
        description: "API 错误码",
        contentType: "application/json",
        schema: errorCodeSchema,
      },
    },
    auth: "required",
    risk: "write",
    verificationStatus: "unknown",
    sources: ["legacy-openapi", "live-probe"],
  },
  {
    method: "PUT",
    path: "/me/topic-view-mode",
    operationId: "putMeTopicViewMode",
    summary: "Set current user's topic view mode",
    tags: ["Me"],
    parameters: [{ name: "mode", in: "query", required: true, schema: z.number(), probeValue: 0 }],
    responses: {
      "200": { description: "Success" },
      default: {
        description: "API 错误码",
        contentType: "application/json",
        schema: errorCodeSchema,
      },
    },
    auth: "required",
    risk: "write",
    verificationStatus: "unknown",
    sources: ["legacy-openapi", "live-probe"],
  },
  {
    method: "PUT",
    path: "/me/followee/{userId}",
    operationId: "putMeFolloweeUserId",
    summary: "Follow user",
    tags: ["Me", "User"],
    parameters: [{ name: "userId", in: "path", required: true, schema: z.number(), probeValue: 1 }],
    responses: {
      "200": { description: "Success" },
      default: {
        description: "API 错误码",
        contentType: "application/json",
        schema: errorCodeSchema,
      },
    },
    auth: "required",
    risk: "write",
    verificationStatus: "verified-authenticated",
    sources: ["legacy-openapi", "live-probe"],
  },
  {
    method: "DELETE",
    path: "/me/followee/{userId}",
    operationId: "deleteMeFolloweeUserId",
    summary: "Unfollow user",
    tags: ["Me", "User"],
    parameters: [{ name: "userId", in: "path", required: true, schema: z.number(), probeValue: 1 }],
    responses: {
      "200": { description: "Success" },
      default: {
        description: "API 错误码",
        contentType: "application/json",
        schema: errorCodeSchema,
      },
    },
    auth: "required",
    risk: "write",
    verificationStatus: "verified-authenticated",
    sources: ["legacy-openapi", "live-probe"],
  },
  {
    method: "GET",
    path: "/me/followee",
    operationId: "getMeFollowee",
    summary: "Get followed user ids",
    tags: ["Me", "User"],
    parameters: [
      { name: "from", in: "query", required: true, schema: z.number(), probeValue: 0 },
      { name: "size", in: "query", required: true, schema: z.number(), probeValue: 2 },
    ],
    responses: {
      "200": {
        description: "User ids",
        contentType: "application/json",
        schema: z.array(z.number()),
      },
      default: {
        description: "API 错误码",
        contentType: "application/json",
        schema: errorCodeSchema,
      },
    },
    auth: "required",
    risk: "account-scoped",
    verificationStatus: "verified-authenticated",
    sources: ["legacy-openapi", "live-probe"],
  },
  {
    method: "GET",
    path: "/me/follower",
    operationId: "getMeFollower",
    summary: "Get follower user ids",
    tags: ["Me", "User"],
    parameters: [
      { name: "from", in: "query", required: true, schema: z.number(), probeValue: 0 },
      { name: "size", in: "query", required: true, schema: z.number(), probeValue: 2 },
    ],
    responses: {
      "200": {
        description: "User ids",
        contentType: "application/json",
        schema: z.array(z.number()),
      },
      default: {
        description: "API 错误码",
        contentType: "application/json",
        schema: errorCodeSchema,
      },
    },
    auth: "required",
    risk: "account-scoped",
    verificationStatus: "verified-authenticated",
    sources: ["legacy-openapi", "live-probe"],
  },
  {
    method: "GET",
    path: "/me/followee/topic",
    operationId: "getMeFolloweeTopic",
    summary: "Get topic feed from followed users",
    tags: ["Me", "Topic"],
    parameters: [
      { name: "from", in: "query", required: true, schema: z.number(), probeValue: 0 },
      { name: "size", in: "query", required: true, schema: z.number(), probeValue: 2 },
      { name: "order", in: "query", required: false, schema: z.number() },
    ],
    responses: {
      "200": {
        description: "Topics",
        contentType: "application/json",
        schema: z.array(topicSchema),
      },
      default: {
        description: "API 错误码",
        contentType: "application/json",
        schema: errorCodeSchema,
      },
    },
    auth: "required",
    risk: "account-scoped",
    verificationStatus: "verified-authenticated",
    sources: ["legacy-openapi", "live-probe"],
  },
  {
    method: "PUT",
    path: "/me/custom-board/{boardId}",
    operationId: "putMeCustomBoardBoardId",
    summary: "Follow board",
    tags: ["Me", "Board"],
    parameters: [
      { name: "boardId", in: "path", required: true, schema: z.number(), probeValue: 758 },
    ],
    responses: {
      "200": { description: "Success" },
      default: {
        description: "API 错误码",
        contentType: "application/json",
        schema: errorCodeSchema,
      },
    },
    auth: "required",
    risk: "write",
    verificationStatus: "verified-authenticated",
    sources: ["legacy-openapi", "live-probe"],
  },
  {
    method: "DELETE",
    path: "/me/custom-board/{boardId}",
    operationId: "deleteMeCustomBoardBoardId",
    summary: "Unfollow board",
    tags: ["Me", "Board"],
    parameters: [
      { name: "boardId", in: "path", required: true, schema: z.number(), probeValue: 758 },
    ],
    responses: {
      "200": { description: "Success" },
      default: {
        description: "API 错误码",
        contentType: "application/json",
        schema: errorCodeSchema,
      },
    },
    auth: "required",
    risk: "write",
    verificationStatus: "verified-authenticated",
    sources: ["legacy-openapi", "live-probe"],
  },
  {
    method: "GET",
    path: "/me/custom-board/topic",
    operationId: "getMeCustomBoardTopic",
    summary: "Get topic feed from followed boards",
    tags: ["Me", "Board", "Topic"],
    parameters: [
      { name: "from", in: "query", required: true, schema: z.number(), probeValue: 0 },
      { name: "size", in: "query", required: true, schema: z.number(), probeValue: 2 },
    ],
    responses: {
      "200": {
        description: "Topics",
        contentType: "application/json",
        schema: z.array(topicSchema),
      },
      default: {
        description: "API 错误码",
        contentType: "application/json",
        schema: errorCodeSchema,
      },
    },
    auth: "required",
    risk: "account-scoped",
    verificationStatus: "verified-authenticated",
    sources: ["legacy-openapi", "live-probe"],
  },
  {
    method: "PUT",
    path: "/me/favorite/{topicId}",
    operationId: "putMeFavoriteTopicId",
    summary: "Favorite topic",
    tags: ["Me", "Topic"],
    parameters: [
      { name: "topicId", in: "path", required: true, schema: z.number(), probeValue: 6572083 },
      { name: "groupid", in: "query", required: false, schema: z.number() },
    ],
    responses: {
      "200": { description: "Success" },
      default: {
        description: "API 错误码",
        contentType: "application/json",
        schema: errorCodeSchema,
      },
    },
    auth: "required",
    risk: "write",
    verificationStatus: "verified-authenticated",
    sources: ["legacy-openapi", "live-probe"],
  },
  {
    method: "DELETE",
    path: "/me/favorite/{topicId}",
    operationId: "deleteMeFavoriteTopicId",
    summary: "Unfavorite topic",
    tags: ["Me", "Topic"],
    parameters: [
      { name: "topicId", in: "path", required: true, schema: z.number(), probeValue: 6572083 },
    ],
    responses: {
      "200": { description: "Success" },
      default: {
        description: "API 错误码",
        contentType: "application/json",
        schema: errorCodeSchema,
      },
    },
    auth: "required",
    risk: "write",
    verificationStatus: "verified-authenticated",
    sources: ["legacy-openapi", "live-probe"],
  },
  {
    method: "GET",
    path: "/me/favorite-topic-group",
    operationId: "getMeFavoriteTopicGroup",
    summary: "Get favorite topic groups",
    tags: ["Me", "Topic"],
    parameters: [],
    responses: {
      "200": {
        description: "Favorite groups",
        contentType: "application/json",
        schema: pagedFavoriteTopicGroupSchema,
      },
      default: {
        description: "API 错误码",
        contentType: "application/json",
        schema: errorCodeSchema,
      },
    },
    auth: "required",
    risk: "account-scoped",
    verificationStatus: "verified-authenticated",
    sources: ["legacy-openapi", "live-probe"],
  },
  {
    method: "POST",
    path: "/me/favorite-topic-group",
    operationId: "postMeFavoriteTopicGroup",
    summary: "Create favorite topic group",
    tags: ["Me", "Topic"],
    parameters: [],
    requestBody: {
      required: true,
      contentType: "application/json",
      schema: z.object({ name: z.string() }),
    },
    responses: {
      "200": { description: "Success" },
      default: {
        description: "API 错误码",
        contentType: "application/json",
        schema: errorCodeSchema,
      },
    },
    auth: "required",
    risk: "write",
    verificationStatus: "verified-authenticated",
    sources: ["legacy-openapi", "live-probe"],
  },
  {
    method: "PUT",
    path: "/me/favorite-topic-group",
    operationId: "putMeFavoriteTopicGroup",
    summary: "Update favorite topic group",
    tags: ["Me", "Topic"],
    parameters: [],
    requestBody: {
      required: true,
      contentType: "application/json",
      schema: z.object({ id: z.number(), name: z.string() }),
    },
    responses: {
      "200": { description: "Success" },
      default: {
        description: "API 错误码",
        contentType: "application/json",
        schema: errorCodeSchema,
      },
    },
    auth: "required",
    risk: "write",
    verificationStatus: "verified-authenticated",
    sources: ["legacy-openapi", "live-probe"],
  },
  {
    method: "DELETE",
    path: "/me/favorite-topic-group",
    operationId: "deleteMeFavoriteTopicGroup",
    summary: "Delete favorite topic group",
    tags: ["Me", "Topic"],
    parameters: [
      { name: "groupid", in: "query", required: true, schema: z.number(), probeValue: 0 },
    ],
    responses: {
      "200": { description: "Success" },
      default: {
        description: "API 错误码",
        contentType: "application/json",
        schema: errorCodeSchema,
      },
    },
    auth: "required",
    risk: "write",
    verificationStatus: "verified-authenticated",
    sources: ["legacy-openapi", "live-probe"],
  },
  {
    method: "GET",
    path: "/me/recent-topic",
    operationId: "getMeRecentTopic",
    summary: "Get current user's recent topics",
    tags: ["Me", "Topic"],
    parameters: [
      { name: "from", in: "query", required: true, schema: z.number(), probeValue: 0 },
      { name: "size", in: "query", required: true, schema: z.number(), probeValue: 2 },
    ],
    responses: {
      "200": {
        description: "Recent topics",
        contentType: "application/json",
        schema: z.array(topicSchema),
      },
      default: {
        description: "API 错误码",
        contentType: "application/json",
        schema: errorCodeSchema,
      },
    },
    auth: "required",
    risk: "account-scoped",
    verificationStatus: "verified-authenticated",
    sources: ["legacy-openapi", "live-probe"],
  },
  {
    method: "GET",
    path: "/me/recent-post",
    operationId: "getMeRecentPost",
    summary: "Get current user's recent posts",
    tags: ["Me", "Post"],
    parameters: [
      { name: "from", in: "query", required: true, schema: z.number(), probeValue: 0 },
      { name: "size", in: "query", required: true, schema: z.number(), probeValue: 2 },
    ],
    responses: {
      "200": {
        description: "Recent posts",
        contentType: "application/json",
        schema: pagedPostResultSchema,
      },
      default: {
        description: "API 错误码",
        contentType: "application/json",
        schema: errorCodeSchema,
      },
    },
    auth: "required",
    risk: "account-scoped",
    verificationStatus: "verified-authenticated",
    sources: ["legacy-openapi", "live-probe"],
  },
  {
    method: "GET",
    path: "/me/hot-post",
    operationId: "getMeHotPost",
    summary: "Get current user's hot posts",
    tags: ["Me", "Post"],
    parameters: [
      { name: "from", in: "query", required: true, schema: z.number(), probeValue: 0 },
      { name: "size", in: "query", required: true, schema: z.number(), probeValue: 2 },
    ],
    responses: {
      "200": {
        description: "Hot posts",
        contentType: "application/json",
        schema: pagedPostResultSchema,
      },
      default: {
        description: "API 错误码",
        contentType: "application/json",
        schema: errorCodeSchema,
      },
    },
    auth: "required",
    risk: "account-scoped",
    verificationStatus: "verified-authenticated",
    sources: ["legacy-openapi", "live-probe"],
  },
  {
    method: "GET",
    path: "/me/browsing-record",
    operationId: "getMeBrowsingRecord",
    summary: "Get current user's browsing history",
    tags: ["Me", "Topic"],
    parameters: [
      { name: "from", in: "query", required: true, schema: z.number(), probeValue: 0 },
      { name: "size", in: "query", required: true, schema: z.number(), probeValue: 2 },
    ],
    responses: {
      "200": {
        description: "Browsing records",
        contentType: "application/json",
        schema: pagedTopicResultDataSchema,
      },
      default: {
        description: "API 错误码",
        contentType: "application/json",
        schema: errorCodeSchema,
      },
    },
    auth: "required",
    risk: "account-scoped",
    verificationStatus: "verified-authenticated",
    sources: ["legacy-openapi", "live-probe"],
  },
  {
    method: "PUT",
    path: "/me/browsing-history",
    operationId: "putMeBrowsingHistory",
    summary: "Enable or disable browsing history",
    tags: ["Me"],
    parameters: [
      { name: "enabled", in: "query", required: true, schema: z.boolean(), probeValue: false },
    ],
    responses: {
      "200": { description: "Success" },
      default: {
        description: "API 错误码",
        contentType: "application/json",
        schema: errorCodeSchema,
      },
    },
    auth: "required",
    risk: "write",
    verificationStatus: "verified-authenticated",
    sources: ["legacy-openapi", "live-probe"],
  },
  {
    method: "PUT",
    path: "/me/transfer-wealth",
    operationId: "putMeTransferWealth",
    summary: "Transfer wealth to users",
    tags: ["Me", "User"],
    parameters: [],
    requestBody: {
      required: true,
      contentType: "application/json",
      schema: transferWealthRequestSchema,
    },
    responses: {
      "200": {
        description: "Successful receiver names",
        contentType: "application/json",
        schema: z.array(z.string()),
      },
      default: {
        description: "API 错误码",
        contentType: "application/json",
        schema: errorCodeSchema,
      },
    },
    auth: "required",
    risk: "write",
    verificationStatus: "unknown",
    sources: ["legacy-openapi", "live-probe"],
  },
  {
    method: "GET",
    path: "/me/unread-count",
    operationId: "getMeUnreadCount",
    summary: "Get unread message and notification counts",
    tags: ["Me", "Message"],
    parameters: [],
    responses: {
      "200": {
        description: "Unread counts",
        contentType: "application/json",
        schema: messageCountsSchema,
      },
      default: {
        description: "API 错误码",
        contentType: "application/json",
        schema: errorCodeSchema,
      },
    },
    auth: "required",
    risk: "account-scoped",
    verificationStatus: "verified-authenticated",
    sources: ["legacy-openapi", "live-probe"],
  },
  {
    method: "GET",
    path: "/me/all-message-count",
    operationId: "getMeAllMessageCount",
    summary: "Get total message and notification counts",
    tags: ["Me", "Message"],
    parameters: [],
    responses: {
      "200": {
        description: "Total counts",
        contentType: "application/json",
        schema: messageCountsSchema,
      },
      default: {
        description: "API 错误码",
        contentType: "application/json",
        schema: errorCodeSchema,
      },
    },
    auth: "required",
    risk: "account-scoped",
    verificationStatus: "verified-authenticated",
    sources: ["legacy-openapi", "live-probe"],
  },
  {
    method: "GET",
    path: "/me/signin",
    operationId: "getMeSignin",
    summary: "Get current user's signin state",
    tags: ["Signin", "Me"],
    parameters: [],
    responses: {
      "200": {
        description: "Signin state",
        contentType: "application/json",
        schema: signinInfoSchema,
      },
      default: {
        description: "API 错误码",
        contentType: "application/json",
        schema: errorCodeSchema,
      },
    },
    auth: "required",
    risk: "account-scoped",
    verificationStatus: "verified-authenticated",
    sources: ["legacy-openapi", "live-probe"],
  },
  {
    method: "POST",
    path: "/me/signin",
    operationId: "postMeSignin",
    summary: "Sign in today",
    tags: ["Signin", "Me"],
    parameters: [],
    requestBody: {
      required: false,
      contentType: "application/json",
      schema: z.union([z.string(), z.looseObject({})]),
    },
    responses: {
      "200": { description: "Success" },
      default: {
        description: "API 错误码",
        contentType: "application/json",
        schema: errorCodeSchema,
      },
    },
    auth: "required",
    risk: "write",
    verificationStatus: "unknown",
    sources: ["legacy-openapi", "live-probe"],
    description:
      "The frontend sends raw editor content with application/json; exact backend body shape is unclear.",
  },
  {
    method: "GET",
    path: "/me/signin-in-month",
    operationId: "getMeSigninInMonth",
    summary: "Get signin records in a month",
    tags: ["Signin", "Me"],
    parameters: [
      { name: "year", in: "query", required: true, schema: z.number(), probeValue: 2025 },
      { name: "month", in: "query", required: true, schema: z.number(), probeValue: 7 },
    ],
    responses: {
      "200": {
        description: "Signin records",
        contentType: "application/json",
        schema: z.array(signinRecordSchema),
      },
      default: {
        description: "API 错误码",
        contentType: "application/json",
        schema: errorCodeSchema,
      },
    },
    auth: "required",
    risk: "account-scoped",
    verificationStatus: "verified-authenticated",
    sources: ["legacy-openapi", "live-probe"],
  },
  {
    method: "POST",
    path: "/me/make-up-missed-signin",
    operationId: "postMeMakeUpMissedSignin",
    summary: "Make up missed signin",
    tags: ["Signin", "Me"],
    parameters: [],
    responses: {
      "200": {
        description: "Make-up result",
        contentType: "application/json",
        schema: makeUpSigninResultSchema,
      },
      default: {
        description: "API 错误码",
        contentType: "application/json",
        schema: errorCodeSchema,
      },
    },
    auth: "required",
    risk: "write",
    verificationStatus: "unknown",
    sources: ["legacy-openapi", "live-probe"],
  },
  {
    method: "GET",
    path: "/me/annual-review-2022",
    operationId: "getMeAnnualReview2022",
    summary: "Get annual review for 2022",
    tags: ["AnnualReview", "Me"],
    parameters: [],
    responses: {
      "200": {
        description: "Annual review",
        contentType: "application/json",
        schema: annualReviewSchema,
      },
      default: {
        description: "API 错误码",
        contentType: "application/json",
        schema: errorCodeSchema,
      },
    },
    auth: "required",
    risk: "account-scoped",
    verificationStatus: "verified-authenticated",
    sources: ["legacy-openapi", "live-probe"],
  },
  {
    method: "GET",
    path: "/me/annual-review-{year}",
    operationId: "getMeAnnualReviewYear",
    summary: "Get annual review by year",
    tags: ["AnnualReview", "Me"],
    parameters: [
      { name: "year", in: "path", required: true, schema: z.number(), probeValue: 2025 },
    ],
    responses: {
      "200": {
        description: "Annual review",
        contentType: "application/json",
        schema: annualReviewV2Schema,
      },
      default: {
        description: "API 错误码",
        contentType: "application/json",
        schema: errorCodeSchema,
      },
    },
    auth: "required",
    risk: "account-scoped",
    verificationStatus: "verified-authenticated",
    sources: ["legacy-openapi", "live-probe"],
  },
  {
    method: "GET",
    path: "/message/recent-contact-users",
    operationId: "getMessageRecentContactUsers",
    summary: "Get recent private-message contacts",
    tags: ["Message"],
    parameters: [
      { name: "from", in: "query", required: true, schema: z.number(), probeValue: 0 },
      { name: "size", in: "query", required: true, schema: z.number(), probeValue: 2 },
    ],
    responses: {
      "200": {
        description: "Recent contacts",
        contentType: "application/json",
        schema: z.array(recentContactSchema),
      },
      default: {
        description: "API 错误码",
        contentType: "application/json",
        schema: errorCodeSchema,
      },
    },
    auth: "required",
    risk: "account-scoped",
    verificationStatus: "verified-authenticated",
    sources: ["legacy-openapi", "live-probe"],
  },
  {
    method: "GET",
    path: "/message/user/{userId}",
    operationId: "getMessageUserUserId",
    summary: "Get private-message history with a user",
    tags: ["Message"],
    parameters: [
      { name: "userId", in: "path", required: true, schema: z.number(), probeValue: 1 },
      { name: "from", in: "query", required: true, schema: z.number(), probeValue: 0 },
      { name: "size", in: "query", required: true, schema: z.number(), probeValue: 2 },
    ],
    responses: {
      "200": {
        description: "Private messages",
        contentType: "application/json",
        schema: z.array(privateMessageSchema),
      },
      default: {
        description: "API 错误码",
        contentType: "application/json",
        schema: errorCodeSchema,
      },
    },
    auth: "required",
    risk: "account-scoped",
    verificationStatus: "verified-authenticated",
    sources: ["legacy-openapi", "live-probe"],
  },
  {
    method: "POST",
    path: "/message",
    operationId: "postMessage",
    summary: "Send private message",
    tags: ["Message"],
    parameters: [],
    requestBody: {
      required: true,
      contentType: "application/json",
      schema: sendMessageRequestSchema,
    },
    responses: {
      "200": { description: "Success" },
      default: {
        description: "API 错误码",
        contentType: "application/json",
        schema: errorCodeSchema,
      },
    },
    auth: "required",
    risk: "write",
    verificationStatus: "unknown",
    sources: ["legacy-openapi", "live-probe"],
    description:
      "The legacy frontend sends { receiverId, content } as JSON. The success response still needs live verification.",
  },
]);
