import { z } from "zod";
import { defineOperations } from "./types.ts";
import {
  annualReviewSchema,
  annualReviewV2Schema,
  changeUserRequestSchema,
  errorCodeSchema,
  makeUpSigninResultSchema,
  meUserSchema,
  messageCountsSchema,
  pagedFavoriteTopicGroupSchema,
  pagedPostResultSchema,
  pagedTopicResultDataSchema,
  privateMessageSchema,
  recentContactSchema,
  sendMessageRequestSchema,
  signinInfoSchema,
  signinRecordSchema,
  themeSettingSchema,
  topicSchema,
  transferWealthRequestSchema,
  transferWealthResponseSchema,
} from "../schemas/index.ts";

const fromParameter = {
  name: "from",
  in: "query",
  required: true,
  schema: z.number().int().nonnegative(),
  description: "从第几条记录开始获取，0 表示第一条。",
  probeValue: 0,
} as const;

const sizeParameter = {
  name: "size",
  in: "query",
  required: true,
  schema: z.number().int().positive(),
  description: "本次最多返回的记录数量。",
  probeValue: 2,
} as const;

const defaultErrorResponse = {
  description: "API 错误码",
  contentType: "application/json",
  schema: errorCodeSchema,
} as const;

export const meOperations = defineOperations([
  {
    method: "GET",
    path: "/me",
    operationId: "getMe",
    summary: "获取当前用户资料",
    tags: ["Me"],
    parameters: [],
    responses: {
      "200": {
        description: "当前登录用户的详细资料",
        contentType: "application/json",
        schema: meUserSchema,
      },
      default: defaultErrorResponse,
    },
    auth: "required",
    risk: "account-scoped",
    verificationStatus: "verified-authenticated",
    sources: ["legacy-openapi", "live-probe"],
    description:
      "返回当前登录用户的完整资料，包括公开资料、账号状态、隐私设置、关注数据和仅本人可见的联系方式等字段。",
  },
  {
    method: "PUT",
    path: "/me",
    operationId: "putMe",
    summary: "修改当前用户资料",
    tags: ["Me"],
    parameters: [],
    requestBody: {
      required: true,
      contentType: "application/json",
      schema: changeUserRequestSchema,
    },
    responses: {
      "200": { description: "用户资料修改请求已处理" },
      default: defaultErrorResponse,
    },
    auth: "required",
    risk: "write",
    verificationStatus: "unknown",
    sources: ["legacy-openapi", "live-probe"],
    description: "修改当前用户的邮箱、性别、个人简介、QQ、个性签名、生日或展示头衔。",
  },
  {
    method: "PUT",
    path: "/me/portrait",
    operationId: "putMePortrait",
    summary: "修改当前用户头像",
    tags: ["Me"],
    parameters: [],
    requestBody: {
      required: true,
      contentType: "application/json",
      schema: z.string().min(1).meta({ description: "新的头像图片地址。" }),
    },
    responses: {
      "200": { description: "头像地址修改请求已处理" },
      default: defaultErrorResponse,
    },
    auth: "required",
    risk: "write",
    verificationStatus: "unknown",
    sources: ["legacy-openapi", "live-probe"],
    description: "将当前用户头像设置为请求体中的图片地址。上传本地头像时应先调用头像文件上传接口。",
  },
  {
    method: "PUT",
    path: "/me/theme",
    operationId: "putMeTheme",
    summary: "设置当前用户主题皮肤",
    tags: ["Me"],
    parameters: [
      {
        name: "id",
        in: "query",
        required: true,
        schema: z.number().int().nonnegative(),
        description: "主题皮肤编号。",
        probeValue: 0,
      },
    ],
    responses: {
      "200": { description: "主题皮肤设置请求已处理" },
      default: defaultErrorResponse,
    },
    auth: "required",
    risk: "write",
    verificationStatus: "unknown",
    sources: ["legacy-openapi", "live-probe"],
    description: "保存当前用户选择的论坛主题皮肤编号。",
  },
  {
    method: "PUT",
    path: "/me/theme-setting",
    operationId: "putMeThemeSetting",
    summary: "设置当前用户明暗主题规则",
    tags: ["Me"],
    parameters: [],
    requestBody: {
      required: true,
      contentType: "application/json",
      schema: themeSettingSchema,
    },
    responses: {
      "200": { description: "明暗主题规则设置请求已处理" },
      default: defaultErrorResponse,
    },
    auth: "required",
    risk: "write",
    verificationStatus: "unknown",
    sources: ["legacy-openapi", "live-probe"],
    description: "保存当前用户按时间切换主题或跟随浏览器明暗模式的规则。",
  },
  {
    method: "PUT",
    path: "/me/topic-view-mode",
    operationId: "putMeTopicViewMode",
    summary: "设置当前用户新帖浏览模式",
    tags: ["Me"],
    parameters: [
      {
        name: "mode",
        in: "query",
        required: true,
        schema: z.union([z.literal(0), z.literal(1), z.literal(2)]),
        description: "新帖浏览模式：0 为经典列表，1 为卡片列表，2 为媒体模式。",
        probeValue: 0,
      },
    ],
    responses: {
      "200": { description: "新帖浏览模式设置请求已处理" },
      default: defaultErrorResponse,
    },
    auth: "required",
    risk: "write",
    verificationStatus: "unknown",
    sources: ["legacy-openapi", "live-probe"],
    description: "保存当前用户访问新帖页面时默认使用的浏览模式。",
  },
  {
    method: "PUT",
    path: "/me/followee/{userId}",
    operationId: "putMeFolloweeUserId",
    summary: "关注用户",
    tags: ["Me", "User"],
    parameters: [
      {
        name: "userId",
        in: "path",
        required: true,
        schema: z.number().int().positive(),
        description: "需要关注的用户 ID。",
        probeValue: 1,
      },
    ],
    responses: {
      "200": { description: "关注请求已处理" },
      default: defaultErrorResponse,
    },
    auth: "required",
    risk: "write",
    verificationStatus: "unknown",
    sources: ["legacy-openapi", "live-probe"],
    description: "将指定用户加入当前用户的关注列表。",
  },
  {
    method: "DELETE",
    path: "/me/followee/{userId}",
    operationId: "deleteMeFolloweeUserId",
    summary: "取消关注用户",
    tags: ["Me", "User"],
    parameters: [
      {
        name: "userId",
        in: "path",
        required: true,
        schema: z.number().int().positive(),
        description: "需要取消关注的用户 ID。",
        probeValue: 1,
      },
    ],
    responses: {
      "200": { description: "取消关注请求已处理" },
      default: defaultErrorResponse,
    },
    auth: "required",
    risk: "write",
    verificationStatus: "unknown",
    sources: ["legacy-openapi", "live-probe"],
    description: "将指定用户从当前用户的关注列表中移除。",
  },
  {
    method: "GET",
    path: "/me/followee",
    operationId: "getMeFollowee",
    summary: "获取当前用户关注的用户 ID",
    tags: ["Me", "User"],
    parameters: [fromParameter, sizeParameter],
    responses: {
      "200": {
        description: "当前用户关注的用户 ID 列表",
        contentType: "application/json",
        schema: z.array(z.number().meta({ description: "被关注用户 ID。" })),
      },
      default: defaultErrorResponse,
    },
    auth: "required",
    risk: "account-scoped",
    verificationStatus: "verified-authenticated",
    sources: ["legacy-openapi", "live-probe"],
    description: "分页返回当前用户关注的用户 ID。",
  },
  {
    method: "GET",
    path: "/me/follower",
    operationId: "getMeFollower",
    summary: "获取当前用户的粉丝 ID",
    tags: ["Me", "User"],
    parameters: [fromParameter, sizeParameter],
    responses: {
      "200": {
        description: "关注当前用户的用户 ID 列表",
        contentType: "application/json",
        schema: z.array(z.number().meta({ description: "粉丝用户 ID。" })),
      },
      default: defaultErrorResponse,
    },
    auth: "required",
    risk: "account-scoped",
    verificationStatus: "verified-authenticated",
    sources: ["legacy-openapi", "live-probe"],
    description: "分页返回关注当前用户的用户 ID。",
  },
  {
    method: "GET",
    path: "/me/followee/topic",
    operationId: "getMeFolloweeTopic",
    summary: "获取关注用户的主题动态",
    tags: ["Me", "Topic"],
    parameters: [
      fromParameter,
      sizeParameter,
      {
        name: "order",
        in: "query",
        required: false,
        schema: z
          .number()
          .int()
          .meta({ description: "排序方式编号；当前前端使用 0，其他取值含义尚未确认。" }),
        description: "排序方式编号；当前前端使用 0，其他取值含义尚未确认。",
      },
    ],
    responses: {
      "200": {
        description: "关注用户最近发表的主题列表",
        contentType: "application/json",
        schema: z.array(topicSchema),
      },
      default: defaultErrorResponse,
    },
    auth: "required",
    risk: "account-scoped",
    verificationStatus: "verified-authenticated",
    sources: ["legacy-openapi", "live-probe"],
    description: "分页聚合当前用户所关注用户发表的主题。",
  },
  {
    method: "PUT",
    path: "/me/custom-board/{boardId}",
    operationId: "putMeCustomBoardBoardId",
    summary: "关注版面",
    tags: ["Me", "Board"],
    parameters: [
      {
        name: "boardId",
        in: "path",
        required: true,
        schema: z.number().int().positive(),
        description: "需要关注的版面 ID。",
        probeValue: 758,
      },
    ],
    responses: {
      "200": { description: "关注版面请求已处理" },
      default: defaultErrorResponse,
    },
    auth: "required",
    risk: "write",
    verificationStatus: "unknown",
    sources: ["legacy-openapi", "live-probe"],
    description: "将指定版面加入当前用户的关注版面列表。",
  },
  {
    method: "DELETE",
    path: "/me/custom-board/{boardId}",
    operationId: "deleteMeCustomBoardBoardId",
    summary: "取消关注版面",
    tags: ["Me", "Board"],
    parameters: [
      {
        name: "boardId",
        in: "path",
        required: true,
        schema: z.number().int().positive(),
        description: "需要取消关注的版面 ID。",
        probeValue: 758,
      },
    ],
    responses: {
      "200": { description: "取消关注版面请求已处理" },
      default: defaultErrorResponse,
    },
    auth: "required",
    risk: "write",
    verificationStatus: "unknown",
    sources: ["legacy-openapi", "live-probe"],
    description: "将指定版面从当前用户的关注版面列表中移除。",
  },
  {
    method: "GET",
    path: "/me/custom-board/topic",
    operationId: "getMeCustomBoardTopic",
    summary: "获取关注版面的主题动态",
    tags: ["Me", "Board", "Topic"],
    parameters: [fromParameter, sizeParameter],
    responses: {
      "200": {
        description: "关注版面的主题列表",
        contentType: "application/json",
        schema: z.array(topicSchema),
      },
      default: defaultErrorResponse,
    },
    auth: "required",
    risk: "account-scoped",
    verificationStatus: "verified-authenticated",
    sources: ["legacy-openapi", "live-probe"],
    description: "分页聚合当前用户所关注版面中的主题。",
  },
  {
    method: "PUT",
    path: "/me/favorite/{topicId}",
    operationId: "putMeFavoriteTopicId",
    summary: "收藏主题",
    tags: ["Me", "Topic"],
    parameters: [
      {
        name: "topicId",
        in: "path",
        required: true,
        schema: z.number().int().positive(),
        description: "需要收藏的主题 ID。",
        probeValue: 6572083,
      },
      {
        name: "groupid",
        in: "query",
        required: false,
        schema: z
          .number()
          .int()
          .nonnegative()
          .meta({ description: "目标收藏夹 ID；省略时使用默认收藏夹。" }),
        description: "目标收藏夹 ID；省略时使用默认收藏夹。",
      },
    ],
    responses: {
      "200": { description: "收藏主题请求已处理" },
      default: defaultErrorResponse,
    },
    auth: "required",
    risk: "write",
    verificationStatus: "unknown",
    sources: ["legacy-openapi", "live-probe"],
    description: "将指定主题加入当前用户的默认收藏夹或指定收藏夹。",
  },
  {
    method: "DELETE",
    path: "/me/favorite/{topicId}",
    operationId: "deleteMeFavoriteTopicId",
    summary: "取消收藏主题",
    tags: ["Me", "Topic"],
    parameters: [
      {
        name: "topicId",
        in: "path",
        required: true,
        schema: z.number().int().positive(),
        description: "需要取消收藏的主题 ID。",
        probeValue: 6572083,
      },
    ],
    responses: {
      "200": { description: "取消收藏主题请求已处理" },
      default: defaultErrorResponse,
    },
    auth: "required",
    risk: "write",
    verificationStatus: "unknown",
    sources: ["legacy-openapi", "live-probe"],
    description: "从当前用户的收藏中移除指定主题。",
  },
  {
    method: "GET",
    path: "/me/favorite-topic-group",
    operationId: "getMeFavoriteTopicGroup",
    summary: "获取当前用户的主题收藏夹",
    tags: ["Me", "Topic"],
    parameters: [],
    responses: {
      "200": {
        description: "当前用户的主题收藏夹分页结果",
        contentType: "application/json",
        schema: pagedFavoriteTopicGroupSchema,
      },
      default: defaultErrorResponse,
    },
    auth: "required",
    risk: "account-scoped",
    verificationStatus: "verified-authenticated",
    sources: ["legacy-openapi", "live-probe"],
    description: "返回当前用户的默认收藏夹和自定义主题收藏夹。",
  },
  {
    method: "POST",
    path: "/me/favorite-topic-group",
    operationId: "postMeFavoriteTopicGroup",
    summary: "创建主题收藏夹",
    tags: ["Me", "Topic"],
    parameters: [],
    requestBody: {
      required: true,
      contentType: "application/json",
      schema: z
        .object({ name: z.string().trim().min(1).meta({ description: "新收藏夹名称。" }) })
        .meta({ description: "创建主题收藏夹的请求。" }),
    },
    responses: {
      "200": { description: "收藏夹创建请求已处理" },
      default: defaultErrorResponse,
    },
    auth: "required",
    risk: "write",
    verificationStatus: "unknown",
    sources: ["legacy-openapi", "live-probe"],
    description: "为当前用户创建一个自定义主题收藏夹。",
  },
  {
    method: "PUT",
    path: "/me/favorite-topic-group",
    operationId: "putMeFavoriteTopicGroup",
    summary: "重命名主题收藏夹",
    tags: ["Me", "Topic"],
    parameters: [],
    requestBody: {
      required: true,
      contentType: "application/json",
      schema: z
        .object({
          id: z.number().int().nonnegative().meta({ description: "需要重命名的收藏夹 ID。" }),
          name: z.string().trim().min(1).meta({ description: "新的收藏夹名称。" }),
        })
        .meta({ description: "重命名主题收藏夹的请求。" }),
    },
    responses: {
      "200": { description: "收藏夹重命名请求已处理" },
      default: defaultErrorResponse,
    },
    auth: "required",
    risk: "write",
    verificationStatus: "unknown",
    sources: ["legacy-openapi", "live-probe"],
    description: "修改当前用户指定主题收藏夹的名称。",
  },
  {
    method: "DELETE",
    path: "/me/favorite-topic-group",
    operationId: "deleteMeFavoriteTopicGroup",
    summary: "删除主题收藏夹",
    tags: ["Me", "Topic"],
    parameters: [
      {
        name: "groupid",
        in: "query",
        required: true,
        schema: z.number().int().nonnegative(),
        description: "需要删除的收藏夹 ID。",
        probeValue: 0,
      },
    ],
    responses: {
      "200": { description: "收藏夹删除请求已处理" },
      default: defaultErrorResponse,
    },
    auth: "required",
    risk: "write",
    verificationStatus: "unknown",
    sources: ["legacy-openapi", "live-probe"],
    description: "删除当前用户指定的主题收藏夹。",
  },
  {
    method: "GET",
    path: "/me/recent-topic",
    operationId: "getMeRecentTopic",
    summary: "获取当前用户最近发表的主题",
    tags: ["Me", "Topic"],
    parameters: [fromParameter, sizeParameter],
    responses: {
      "200": {
        description: "当前用户最近发表的主题列表",
        contentType: "application/json",
        schema: z.array(topicSchema),
      },
      default: defaultErrorResponse,
    },
    auth: "required",
    risk: "account-scoped",
    verificationStatus: "verified-authenticated",
    sources: ["legacy-openapi", "live-probe"],
    description: "分页返回当前用户最近发表的主题。",
  },
  {
    method: "GET",
    path: "/me/recent-post",
    operationId: "getMeRecentPost",
    summary: "获取当前用户最近发表的回复",
    tags: ["Me", "Post"],
    parameters: [fromParameter, sizeParameter],
    responses: {
      "200": {
        description: "当前用户最近发表的回复分页结果",
        contentType: "application/json",
        schema: pagedPostResultSchema,
      },
      default: defaultErrorResponse,
    },
    auth: "required",
    risk: "account-scoped",
    verificationStatus: "verified-authenticated",
    sources: ["legacy-openapi", "live-probe"],
    description: "分页返回当前用户最近发表的回复。",
  },
  {
    method: "GET",
    path: "/me/hot-post",
    operationId: "getMeHotPost",
    summary: "获取当前用户的热门回复",
    tags: ["Me", "Post"],
    parameters: [fromParameter, sizeParameter],
    responses: {
      "200": {
        description: "当前用户的热门回复分页结果",
        contentType: "application/json",
        schema: pagedPostResultSchema,
      },
      default: defaultErrorResponse,
    },
    auth: "required",
    risk: "account-scoped",
    verificationStatus: "verified-authenticated",
    sources: ["legacy-openapi", "live-probe"],
    description: "分页返回当前用户的热门回复，具体排序规则由服务端决定。",
  },
  {
    method: "GET",
    path: "/me/browsing-record",
    operationId: "getMeBrowsingRecord",
    summary: "获取当前用户的浏览历史",
    tags: ["Me", "Topic"],
    parameters: [fromParameter, sizeParameter],
    responses: {
      "200": {
        description: "当前用户的主题浏览历史分页结果",
        contentType: "application/json",
        schema: pagedTopicResultDataSchema,
      },
      default: defaultErrorResponse,
    },
    auth: "required",
    risk: "account-scoped",
    verificationStatus: "verified-authenticated",
    sources: ["legacy-openapi", "live-probe"],
    description: "分页返回当前用户最近浏览过的主题及最后浏览时间。",
  },
  {
    method: "PUT",
    path: "/me/browsing-history",
    operationId: "putMeBrowsingHistory",
    summary: "设置是否记录浏览历史",
    tags: ["Me"],
    parameters: [
      {
        name: "enabled",
        in: "query",
        required: true,
        schema: z.boolean(),
        description: "是否启用主题浏览历史记录。",
        probeValue: false,
      },
    ],
    responses: {
      "200": { description: "浏览历史设置请求已处理" },
      default: defaultErrorResponse,
    },
    auth: "required",
    risk: "write",
    verificationStatus: "unknown",
    sources: ["legacy-openapi", "live-probe"],
    description: "开启或关闭当前用户的主题浏览历史记录。",
  },
  {
    method: "PUT",
    path: "/me/transfer-wealth",
    operationId: "putMeTransferWealth",
    summary: "向其他用户转账",
    tags: ["Me", "User"],
    parameters: [],
    requestBody: {
      required: true,
      contentType: "application/json",
      schema: transferWealthRequestSchema,
    },
    responses: {
      "200": {
        description: "完成转账的收款用户名列表",
        contentType: "application/json",
        schema: transferWealthResponseSchema,
      },
      default: defaultErrorResponse,
    },
    auth: "required",
    risk: "write",
    verificationStatus: "unknown",
    sources: ["legacy-openapi", "live-probe"],
    description:
      "向一个或多个用户分别转出指定财富值。当前前端按转账金额的 10% 与 10 中的较大值计算每笔手续费。",
  },
  {
    method: "GET",
    path: "/me/unread-count",
    operationId: "getMeUnreadCount",
    summary: "获取未读消息数量",
    tags: ["Me", "Message"],
    parameters: [],
    responses: {
      "200": {
        description: "各类未读消息和通知数量",
        contentType: "application/json",
        schema: messageCountsSchema,
      },
      default: defaultErrorResponse,
    },
    auth: "required",
    risk: "account-scoped",
    verificationStatus: "verified-authenticated",
    sources: ["legacy-openapi", "live-probe"],
    description: "返回当前用户未读的系统通知、@ 提及、回复通知和私信数量。",
  },
  {
    method: "GET",
    path: "/me/all-message-count",
    operationId: "getMeAllMessageCount",
    summary: "获取全部消息数量",
    tags: ["Me", "Message"],
    parameters: [],
    responses: {
      "200": {
        description: "各类消息和通知总数",
        contentType: "application/json",
        schema: messageCountsSchema,
      },
      default: defaultErrorResponse,
    },
    auth: "required",
    risk: "account-scoped",
    verificationStatus: "verified-authenticated",
    sources: ["legacy-openapi", "live-probe"],
    description: "返回当前用户收到的系统通知、@ 提及、回复通知和私信总数。",
  },
  {
    method: "GET",
    path: "/me/signin",
    operationId: "getMeSignin",
    summary: "获取当前用户签到状态",
    tags: ["Signin", "Me"],
    parameters: [],
    responses: {
      "200": {
        description: "当前用户的签到状态",
        contentType: "application/json",
        schema: signinInfoSchema,
      },
      default: defaultErrorResponse,
    },
    auth: "required",
    risk: "account-scoped",
    verificationStatus: "verified-authenticated",
    sources: ["legacy-openapi", "live-probe"],
    description: "返回当前用户今天是否已签到、连续签到天数、最近签到时间和最近一次奖励。",
  },
  {
    method: "POST",
    path: "/me/signin",
    operationId: "postMeSignin",
    summary: "执行今日签到",
    tags: ["Signin", "Me"],
    parameters: [],
    requestBody: {
      required: false,
      contentType: "application/json",
      schema: z
        .union([
          z.string().meta({ description: "可选的签到留言。" }),
          z
            .looseObject({})
            .meta({ description: "兼容旧接口的签到配置对象，内部字段含义尚未确认。" }),
        ])
        .meta({ description: "可选签到内容；当前前端提交字符串，未填写时提交空字符串。" }),
    },
    responses: {
      "200": { description: "签到请求已处理" },
      default: defaultErrorResponse,
    },
    auth: "required",
    risk: "write",
    verificationStatus: "unknown",
    sources: ["legacy-openapi", "live-probe"],
    description: "为当前用户执行当天签到，并可附带签到留言。",
  },
  {
    method: "GET",
    path: "/me/signin-in-month",
    operationId: "getMeSigninInMonth",
    summary: "获取指定月份的签到记录",
    tags: ["Signin", "Me"],
    parameters: [
      {
        name: "year",
        in: "query",
        required: true,
        schema: z.number().int(),
        description: "需要查询的年份。",
        probeValue: 2025,
      },
      {
        name: "month",
        in: "query",
        required: true,
        schema: z.number().int().min(1).max(12),
        description: "需要查询的月份，取值为 1 至 12。",
        probeValue: 7,
      },
    ],
    responses: {
      "200": {
        description: "指定月份的签到记录列表",
        contentType: "application/json",
        schema: z.array(signinRecordSchema),
      },
      default: defaultErrorResponse,
    },
    auth: "required",
    risk: "account-scoped",
    verificationStatus: "verified-authenticated",
    sources: ["legacy-openapi", "live-probe"],
    description: "返回当前用户在指定年月中的每日签到和补签记录。",
  },
  {
    method: "POST",
    path: "/me/make-up-missed-signin",
    operationId: "postMeMakeUpMissedSignin",
    summary: "使用补签卡补签",
    tags: ["Signin", "Me"],
    parameters: [],
    responses: {
      "200": {
        description: "补签处理结果",
        contentType: "application/json",
        schema: makeUpSigninResultSchema,
      },
      default: defaultErrorResponse,
    },
    auth: "required",
    risk: "write",
    verificationStatus: "unknown",
    sources: ["legacy-openapi", "live-probe"],
    description: "消耗当前用户的一张补签卡补签缺失日期，具体补签日期由服务端决定。",
  },
  {
    method: "GET",
    path: "/me/annual-review-2022",
    operationId: "getMeAnnualReview2022",
    summary: "获取 2022 年度报告",
    tags: ["AnnualReview", "Me"],
    parameters: [],
    responses: {
      "200": {
        description: "当前用户的 2022 年度报告",
        contentType: "application/json",
        schema: annualReviewSchema,
      },
      default: defaultErrorResponse,
    },
    auth: "required",
    risk: "account-scoped",
    verificationStatus: "verified-authenticated",
    sources: ["legacy-openapi", "live-probe"],
    description: "返回当前用户 2022 年的发帖、互动、活跃版面和发言时段等年度统计。",
  },
  {
    method: "GET",
    path: "/me/annual-review-{year}",
    operationId: "getMeAnnualReviewYear",
    summary: "获取指定年份的年度报告",
    tags: ["AnnualReview", "Me"],
    parameters: [
      {
        name: "year",
        in: "path",
        required: true,
        schema: z.number().int(),
        description: "年度报告对应年份。",
        probeValue: 2025,
      },
    ],
    responses: {
      "200": {
        description: "当前用户指定年份的年度报告",
        contentType: "application/json",
        schema: annualReviewV2Schema,
      },
      default: defaultErrorResponse,
    },
    auth: "required",
    risk: "account-scoped",
    verificationStatus: "verified-authenticated",
    sources: ["legacy-openapi", "live-probe"],
    description:
      "返回当前用户指定年份的发帖、互动、活跃版面、点赞关联用户、抽卡和竞猜等年度统计。不同年份可能省略不适用的模块。",
  },
  {
    method: "GET",
    path: "/message/recent-contact-users",
    operationId: "getMessageRecentContactUsers",
    summary: "获取最近私信联系人",
    tags: ["Message"],
    parameters: [fromParameter, sizeParameter],
    responses: {
      "200": {
        description: "最近私信联系人及会话摘要列表",
        contentType: "application/json",
        schema: z.array(recentContactSchema),
      },
      default: defaultErrorResponse,
    },
    auth: "required",
    risk: "account-scoped",
    verificationStatus: "verified-authenticated",
    sources: ["legacy-openapi", "live-probe"],
    description: "分页返回当前用户最近的私信联系人，以及每个会话的最近消息摘要。",
  },
  {
    method: "GET",
    path: "/message/user/{userId}",
    operationId: "getMessageUserUserId",
    summary: "获取与指定用户的私信记录",
    tags: ["Message"],
    parameters: [
      {
        name: "userId",
        in: "path",
        required: true,
        schema: z.number().int().positive(),
        description: "私信会话另一方的用户 ID。",
        probeValue: 1,
      },
      fromParameter,
      sizeParameter,
    ],
    responses: {
      "200": {
        description: "当前用户与指定用户之间的私信列表",
        contentType: "application/json",
        schema: z.array(privateMessageSchema),
      },
      default: defaultErrorResponse,
    },
    auth: "required",
    risk: "account-scoped",
    verificationStatus: "verified-authenticated",
    sources: ["legacy-openapi", "live-probe"],
    description: "分页返回当前用户与指定用户之间的双向私信记录。",
  },
  {
    method: "POST",
    path: "/message",
    operationId: "postMessage",
    summary: "发送私信",
    tags: ["Message"],
    parameters: [],
    requestBody: {
      required: true,
      contentType: "application/json",
      schema: sendMessageRequestSchema,
    },
    responses: {
      "200": { description: "私信发送请求已处理" },
      default: defaultErrorResponse,
    },
    auth: "required",
    risk: "write",
    verificationStatus: "unknown",
    sources: ["legacy-openapi", "live-probe"],
    description: "向指定用户发送一条私信。请求体包含收信用户 ID 和私信正文。",
  },
]);
