import { z } from "zod";
import { defineOperations } from "./types.ts";
import {
  createPostRequestSchema,
  editPostRequestSchema,
  errorCodeSchema,
  likeSchema,
  postSchema,
  postOperationRequestSchema,
  ratingReasonSchema,
  reasonRequestSchema,
} from "../schemas/index.ts";

export const postOperations = defineOperations([
  {
    method: "PUT",
    path: "/post/{postId}",
    operationId: "putPostPostId",
    summary: "Edit post",
    tags: ["Post"],
    parameters: [
      { name: "postId", in: "path", required: true, schema: z.number(), probeValue: 124447422 },
    ],
    requestBody: { required: true, contentType: "application/json", schema: editPostRequestSchema },
    responses: {
      "200": { description: "Success" },
      default: {
        description: "API 错误码",
        contentType: "application/json",
        schema: errorCodeSchema,
      },
    },
    auth: "required",
    risk: "write",
    verificationStatus: "unknown",
    sources: ["legacy-openapi", "live-probe"],
  },
  {
    method: "DELETE",
    path: "/post/{postId}",
    operationId: "deletePostPostId",
    summary: "Delete post",
    tags: ["Post", "Moderation"],
    parameters: [
      { name: "postId", in: "path", required: true, schema: z.number(), probeValue: 124447422 },
    ],
    requestBody: { required: false, contentType: "application/json", schema: reasonRequestSchema },
    responses: {
      "200": { description: "Success" },
      default: {
        description: "API 错误码",
        contentType: "application/json",
        schema: errorCodeSchema,
      },
    },
    auth: "required",
    risk: "destructive",
    verificationStatus: "unknown",
    sources: ["legacy-openapi", "live-probe"],
  },
  {
    method: "GET",
    path: "/post/{postId}/original",
    operationId: "getPostPostIdOriginal",
    summary: "Get original post content for editing",
    tags: ["Post"],
    parameters: [
      { name: "postId", in: "path", required: true, schema: z.number(), probeValue: 124447422 },
    ],
    responses: {
      "200": {
        description: "Original post data",
        contentType: "application/json",
        schema: postSchema,
      },
      default: {
        description: "API 错误码",
        contentType: "application/json",
        schema: errorCodeSchema,
      },
    },
    auth: "required",
    risk: "read-only",
    verificationStatus: "permission-denied",
    sources: ["legacy-openapi", "live-probe"],
  },
  {
    method: "GET",
    path: "/post/{postId}/like",
    operationId: "getPostPostIdLike",
    summary: "Get post like state and counts",
    tags: ["Post"],
    parameters: [
      { name: "postId", in: "path", required: true, schema: z.number(), probeValue: 124447422 },
    ],
    responses: {
      "200": { description: "Like state", contentType: "application/json", schema: likeSchema },
      default: {
        description: "API 错误码",
        contentType: "application/json",
        schema: errorCodeSchema,
      },
    },
    auth: "anonymous",
    risk: "read-only",
    verificationStatus: "verified-anonymous",
    sources: ["legacy-openapi", "live-probe"],
  },
  {
    method: "PUT",
    path: "/post/{postId}/like",
    operationId: "putPostPostIdLike",
    summary: "Like or dislike a post",
    tags: ["Post"],
    parameters: [
      { name: "postId", in: "path", required: true, schema: z.number(), probeValue: 124447422 },
    ],
    requestBody: {
      required: true,
      contentType: "application/json",
      schema: z.union([z.literal("1"), z.literal("2")]),
    },
    responses: {
      "200": { description: "Success" },
      default: {
        description: "API 错误码",
        contentType: "application/json",
        schema: errorCodeSchema,
      },
    },
    auth: "required",
    risk: "write",
    verificationStatus: "unknown",
    sources: ["legacy-openapi", "live-probe"],
  },
  {
    method: "GET",
    path: "/post/basic",
    operationId: "getPostBasic",
    summary: "Get basic post info by repeated id query",
    tags: ["Post"],
    parameters: [
      { name: "id", in: "query", required: true, schema: z.array(z.number()), probeValue: 758 },
    ],
    responses: {
      "200": {
        description: "Basic posts",
        contentType: "application/json",
        schema: z.array(postSchema),
      },
      default: {
        description: "API 错误码",
        contentType: "application/json",
        schema: errorCodeSchema,
      },
    },
    auth: "required",
    risk: "read-only",
    verificationStatus: "unknown",
    sources: ["legacy-openapi", "live-probe"],
    deprecated: true,
    description: "旧前端曾使用该读取接口；2026-07-11 实测返回 405，当前路由仅允许 PUT 和 DELETE。",
  },
  {
    method: "GET",
    path: "/post/topic/user",
    operationId: "getPostTopicUser",
    summary: "Get one user's posts in a topic",
    tags: ["Post", "Topic"],
    parameters: [
      { name: "topicid", in: "query", required: true, schema: z.number(), probeValue: 6572083 },
      { name: "userid", in: "query", required: true, schema: z.number(), probeValue: 1 },
      { name: "from", in: "query", required: true, schema: z.number(), probeValue: 0 },
      { name: "size", in: "query", required: true, schema: z.number(), probeValue: 2 },
    ],
    responses: {
      "200": { description: "Posts", contentType: "application/json", schema: z.array(postSchema) },
      default: {
        description: "API 错误码",
        contentType: "application/json",
        schema: errorCodeSchema,
      },
    },
    auth: "required",
    risk: "read-only",
    verificationStatus: "unknown",
    sources: ["legacy-openapi", "live-probe"],
  },
  {
    method: "GET",
    path: "/post/topic/specific-user",
    operationId: "getPostTopicSpecificUser",
    summary: "Trace replies related to a specific post user",
    tags: ["Post", "Topic"],
    parameters: [
      { name: "topicid", in: "query", required: true, schema: z.number(), probeValue: 6572083 },
      { name: "postid", in: "query", required: true, schema: z.number(), probeValue: 124447422 },
      { name: "from", in: "query", required: true, schema: z.number(), probeValue: 0 },
      { name: "size", in: "query", required: true, schema: z.number(), probeValue: 2 },
    ],
    responses: {
      "200": { description: "Posts", contentType: "application/json", schema: z.array(postSchema) },
      default: {
        description: "API 错误码",
        contentType: "application/json",
        schema: errorCodeSchema,
      },
    },
    auth: "required",
    risk: "read-only",
    verificationStatus: "unknown",
    sources: ["legacy-openapi", "live-probe"],
  },
  {
    method: "GET",
    path: "/post/topic/anonymous/user",
    operationId: "getPostTopicAnonymousUser",
    summary: "Trace anonymous replies related to a specific post",
    tags: ["Post", "Topic"],
    parameters: [
      { name: "topicid", in: "query", required: true, schema: z.number(), probeValue: 6572083 },
      { name: "postid", in: "query", required: true, schema: z.number(), probeValue: 124447422 },
      { name: "from", in: "query", required: true, schema: z.number(), probeValue: 0 },
      { name: "size", in: "query", required: true, schema: z.number(), probeValue: 2 },
    ],
    responses: {
      "200": { description: "Posts", contentType: "application/json", schema: z.array(postSchema) },
      default: {
        description: "API 错误码",
        contentType: "application/json",
        schema: errorCodeSchema,
      },
    },
    auth: "required",
    risk: "read-only",
    verificationStatus: "unknown",
    sources: ["legacy-openapi", "live-probe"],
  },
  {
    method: "PUT",
    path: "/post/{postId}/rating",
    operationId: "putPostPostIdRating",
    summary: "Rate a post, legacy version",
    tags: ["Post"],
    parameters: [
      { name: "postId", in: "path", required: true, schema: z.number(), probeValue: 124447422 },
    ],
    requestBody: {
      required: true,
      contentType: "application/json",
      schema: z.object({ value: z.union([z.literal(-1), z.literal(1)]), reason: z.string() }),
    },
    responses: {
      "200": { description: "Success" },
      default: {
        description: "API 错误码",
        contentType: "application/json",
        schema: errorCodeSchema,
      },
    },
    auth: "required",
    risk: "write",
    verificationStatus: "unknown",
    sources: ["legacy-openapi", "live-probe"],
  },
  {
    method: "PUT",
    path: "/post/{postId}/rating-v2",
    operationId: "putPostPostIdRatingV2",
    summary: "Rate a post, v2 reason based version",
    tags: ["Post"],
    parameters: [
      { name: "postId", in: "path", required: true, schema: z.number(), probeValue: 124447422 },
    ],
    requestBody: {
      required: true,
      contentType: "application/json",
      schema: z.object({ reasonId: z.number(), type: z.union([z.literal(1), z.literal(2)]) }),
    },
    responses: {
      "200": { description: "Success" },
      default: {
        description: "API 错误码",
        contentType: "application/json",
        schema: errorCodeSchema,
      },
    },
    auth: "required",
    risk: "write",
    verificationStatus: "unknown",
    sources: ["legacy-openapi", "live-probe"],
  },
  {
    method: "POST",
    path: "/post/{postId}/operation",
    operationId: "postPostPostIdOperation",
    summary: "Perform post management operation",
    tags: ["Post", "Moderation"],
    parameters: [
      { name: "postId", in: "path", required: true, schema: z.number(), probeValue: 124447422 },
    ],
    requestBody: {
      required: true,
      contentType: "application/json",
      schema: postOperationRequestSchema,
    },
    responses: {
      "200": { description: "Success" },
      default: {
        description: "API 错误码",
        contentType: "application/json",
        schema: errorCodeSchema,
      },
    },
    auth: "required",
    risk: "destructive",
    verificationStatus: "unknown",
    sources: ["legacy-openapi", "live-probe"],
    description:
      "Used for wealth, prestige, and board mute operations. Exact enum values are inferred.",
  },
  {
    method: "GET",
    path: "/post/{postId}/awards",
    operationId: "getPostPostIdAwards",
    summary: "Get post awards or ratings",
    tags: ["Post"],
    parameters: [
      { name: "postId", in: "path", required: true, schema: z.number(), probeValue: 124447422 },
    ],
    responses: {
      "200": {
        description: "Award list",
        contentType: "application/json",
        schema: z.array(z.looseObject({})),
      },
      default: {
        description: "API 错误码",
        contentType: "application/json",
        schema: errorCodeSchema,
      },
    },
    auth: "anonymous",
    risk: "read-only",
    verificationStatus: "verified-anonymous",
    sources: ["legacy-openapi", "live-probe"],
  },
  {
    method: "GET",
    path: "/manage/reward-daily-record",
    operationId: "getManageRewardDailyRecord",
    summary: "Query daily reward records for a board",
    tags: ["Moderation"],
    parameters: [
      { name: "boardId", in: "query", required: true, schema: z.number(), probeValue: 758 },
    ],
    responses: {
      "200": {
        description: "Reward daily records",
        contentType: "application/json",
        schema: z.looseObject({}),
      },
      default: {
        description: "API 错误码",
        contentType: "application/json",
        schema: errorCodeSchema,
      },
    },
    auth: "required",
    risk: "destructive",
    verificationStatus: "permission-denied",
    sources: ["legacy-openapi", "live-probe"],
  },
  {
    method: "GET",
    path: "/post/rating-reason",
    operationId: "getPostRatingReason",
    summary: "Get available post rating reasons",
    tags: ["Post"],
    parameters: [
      {
        name: "type",
        in: "query",
        required: true,
        schema: z.union([z.literal(1), z.literal(2)]),
        probeValue: 1,
      },
    ],
    responses: {
      "200": {
        description: "Available rating reasons",
        contentType: "application/json",
        schema: z.array(ratingReasonSchema),
      },
    },
    auth: "anonymous",
    risk: "read-only",
    verificationStatus: "verified-anonymous",
    sources: ["legacy-openapi", "live-probe"],
  },
  {
    method: "POST",
    path: "/post/topic/{topicId}",
    operationId: "postPostTopicTopicId",
    summary: "Reply to a topic using the legacy route",
    tags: ["Post", "Topic"],
    parameters: [
      { name: "topicId", in: "path", required: true, schema: z.number(), probeValue: 6572083 },
    ],
    requestBody: {
      required: true,
      contentType: "application/json",
      schema: createPostRequestSchema,
    },
    responses: { "200": { description: "Success" } },
    auth: "required",
    risk: "write",
    verificationStatus: "unknown",
    sources: ["legacy-openapi", "live-probe"],
    deprecated: true,
  },
]);
