import { z } from "zod";
import { defineOperations } from "./types.ts";
import {
  createPostRequestSchema,
  editPostRequestSchema,
  errorCodeSchema,
  likeSchema,
  postAwardSchema,
  postLikeActionSchema,
  postSchema,
  postOperationRequestSchema,
  postRewardDailyRecordSchema,
  postRatingRequestSchema,
  postRatingTypeSchema,
  ratingReasonSchema,
  reasonRequestSchema,
} from "../schemas/index.ts";

export const postOperations = defineOperations([
  {
    method: "PUT",
    path: "/post/{postId}",
    operationId: "putPostPostId",
    summary: "编辑帖子",
    tags: ["Post"],
    parameters: [
      {
        name: "postId",
        in: "path",
        required: true,
        schema: z.number().int().positive(),
        description: "需要编辑的帖子 ID。",
        probeValue: 124447422,
      },
    ],
    requestBody: { required: true, contentType: "application/json", schema: editPostRequestSchema },
    responses: {
      "200": { description: "帖子修改成功" },
      default: {
        description: "API 错误码",
        contentType: "application/json",
        schema: errorCodeSchema,
      },
    },
    auth: "required",
    risk: "write",
    verificationStatus: "verified-write",
    sources: ["legacy-openapi", "live-probe"],
    description:
      "修改指定帖子的正文。编辑主题首帖时，还可以同步修改主题标题、标签、主题类型和消息提醒设置。",
  },
  {
    method: "DELETE",
    path: "/post/{postId}",
    operationId: "deletePostPostId",
    summary: "删除帖子",
    tags: ["Post", "Moderation"],
    parameters: [
      {
        name: "postId",
        in: "path",
        required: true,
        schema: z.number().int().positive(),
        description: "需要删除的帖子 ID。",
        probeValue: 124447422,
      },
    ],
    requestBody: { required: false, contentType: "application/json", schema: reasonRequestSchema },
    responses: {
      "200": { description: "帖子删除成功" },
      default: {
        description: "API 错误码",
        contentType: "application/json",
        schema: errorCodeSchema,
      },
    },
    auth: "required",
    risk: "destructive",
    verificationStatus: "permission-denied",
    sources: ["legacy-openapi", "live-probe"],
    description: "删除指定帖子，可在请求体中提供删除理由。",
  },
  {
    method: "GET",
    path: "/post/{postId}/original",
    operationId: "getPostPostIdOriginal",
    summary: "获取帖子原始内容",
    tags: ["Post"],
    parameters: [
      {
        name: "postId",
        in: "path",
        required: true,
        schema: z.number().int().positive(),
        description: "需要读取原始内容的帖子 ID。",
        probeValue: 124447422,
      },
    ],
    responses: {
      "200": {
        description: "成功获取可编辑的帖子原始内容",
        contentType: "application/json",
        schema: postSchema,
      },
      default: {
        description: "API 错误码",
        contentType: "application/json",
        schema: errorCodeSchema,
      },
    },
    auth: "required",
    risk: "read-only",
    verificationStatus: "verified-authenticated",
    sources: ["legacy-openapi", "live-probe"],
    description:
      "返回帖子未经渲染的正文、格式和楼层等编辑所需信息。当前用户需要具有该帖子的编辑权限。",
  },
  {
    method: "GET",
    path: "/post/{postId}/like",
    operationId: "getPostPostIdLike",
    summary: "获取帖子赞踩状态",
    tags: ["Post"],
    parameters: [
      {
        name: "postId",
        in: "path",
        required: true,
        schema: z.number().int().positive(),
        description: "需要查询赞踩状态的帖子 ID。",
        probeValue: 124447422,
      },
    ],
    responses: {
      "200": {
        description: "成功获取点赞数、点踩数和当前用户状态",
        contentType: "application/json",
        schema: likeSchema,
      },
      default: {
        description: "API 错误码",
        contentType: "application/json",
        schema: errorCodeSchema,
      },
    },
    auth: "anonymous",
    risk: "read-only",
    verificationStatus: "verified-anonymous",
    sources: ["legacy-openapi", "live-probe"],
    description: "返回指定帖子的点赞数、点踩数，以及当前访问者的赞踩状态。",
  },
  {
    method: "PUT",
    path: "/post/{postId}/like",
    operationId: "putPostPostIdLike",
    summary: "点赞或点踩帖子",
    tags: ["Post"],
    parameters: [
      {
        name: "postId",
        in: "path",
        required: true,
        schema: z.number().int().positive(),
        description: "需要点赞或点踩的帖子 ID。",
        probeValue: 124447422,
      },
    ],
    requestBody: {
      required: true,
      contentType: "application/json",
      schema: postLikeActionSchema,
    },
    responses: {
      "200": { description: "赞踩操作成功" },
      default: {
        description: "API 错误码",
        contentType: "application/json",
        schema: errorCodeSchema,
      },
    },
    auth: "required",
    risk: "write",
    verificationStatus: "verified-write",
    sources: ["legacy-openapi", "live-probe"],
    description: "对指定帖子执行点赞或点踩。请求体使用字符串 1 表示点赞，字符串 2 表示点踩。",
  },
  {
    method: "GET",
    path: "/post/basic",
    operationId: "getPostBasic",
    summary: "批量获取帖子基础信息（已弃用）",
    tags: ["Post"],
    parameters: [
      {
        name: "id",
        in: "query",
        required: true,
        schema: z.array(z.number().int().positive()),
        description: "需要查询的帖子 ID，可重复传入多个 id 参数。",
        probeValue: 758,
      },
    ],
    responses: {
      "200": {
        description: "帖子基础信息列表",
        contentType: "application/json",
        schema: z.array(postSchema),
      },
      default: {
        description: "API 错误码",
        contentType: "application/json",
        schema: errorCodeSchema,
      },
    },
    auth: "required",
    risk: "read-only",
    verificationStatus: "conflicted",
    sources: ["legacy-openapi", "live-probe"],
    deprecated: true,
    description: "旧版前端曾按帖子 ID 批量读取基础信息；当前服务不再提供该 GET 路由。",
  },
  {
    method: "GET",
    path: "/post/topic/user",
    operationId: "getPostTopicUser",
    summary: "获取主题内指定用户的帖子（已弃用）",
    tags: ["Post", "Topic"],
    parameters: [
      {
        name: "topicid",
        in: "query",
        required: true,
        schema: z.number().int().positive(),
        description: "主题 ID。",
        probeValue: 6572083,
      },
      {
        name: "userid",
        in: "query",
        required: true,
        schema: z.number().int().positive(),
        description: "需要筛选的用户 ID。",
        probeValue: 1,
      },
      {
        name: "from",
        in: "query",
        required: true,
        schema: z.number().int().nonnegative(),
        description: "起始偏移量，0 表示第一条。",
        probeValue: 0,
      },
      {
        name: "size",
        in: "query",
        required: true,
        schema: z.number().int().positive(),
        description: "本次最多返回的帖子数量。",
        probeValue: 2,
      },
    ],
    responses: {
      "200": {
        description: "指定用户在主题中的帖子列表",
        contentType: "application/json",
        schema: z.array(postSchema),
      },
      default: {
        description: "API 错误码",
        contentType: "application/json",
        schema: errorCodeSchema,
      },
    },
    auth: "required",
    risk: "read-only",
    verificationStatus: "conflicted",
    sources: ["legacy-openapi", "live-probe"],
    deprecated: true,
    description: "旧版前端用于筛选某位用户在主题中的帖子；当前服务不再提供该路由。",
  },
  {
    method: "GET",
    path: "/post/topic/specific-user",
    operationId: "getPostTopicSpecificUser",
    summary: "追踪指定帖子作者的回复",
    tags: ["Post", "Topic"],
    parameters: [
      {
        name: "topicid",
        in: "query",
        required: true,
        schema: z.number().int().positive(),
        description: "需要追踪的主题 ID。",
        probeValue: 6572083,
      },
      {
        name: "postid",
        in: "query",
        required: true,
        schema: z.number().int().positive(),
        description: "用于确定目标作者的帖子 ID。",
        probeValue: 124447422,
      },
      {
        name: "from",
        in: "query",
        required: true,
        schema: z.number().int().nonnegative(),
        description: "起始偏移量，0 表示第一条。",
        probeValue: 0,
      },
      {
        name: "size",
        in: "query",
        required: true,
        schema: z.number().int().positive(),
        description: "本次最多返回的帖子数量。",
        probeValue: 2,
      },
    ],
    responses: {
      "200": {
        description: "目标作者在该主题中的帖子列表",
        contentType: "application/json",
        schema: z.array(postSchema),
      },
      default: {
        description: "API 错误码",
        contentType: "application/json",
        schema: errorCodeSchema,
      },
    },
    auth: "required",
    risk: "read-only",
    verificationStatus: "verified-authenticated",
    sources: ["legacy-openapi", "live-probe"],
    description: "根据 postid 对应的作者，分页返回该作者在指定主题中发布的帖子。",
  },
  {
    method: "GET",
    path: "/post/topic/anonymous/user",
    operationId: "getPostTopicAnonymousUser",
    summary: "追踪匿名帖子作者的回复（已弃用）",
    tags: ["Post", "Topic"],
    parameters: [
      {
        name: "topicid",
        in: "query",
        required: true,
        schema: z.number().int().positive(),
        description: "需要追踪的主题 ID。",
        probeValue: 6572083,
      },
      {
        name: "postid",
        in: "query",
        required: true,
        schema: z.number().int().positive(),
        description: "用于确定匿名作者标识的帖子 ID。",
        probeValue: 124447422,
      },
      {
        name: "from",
        in: "query",
        required: true,
        schema: z.number().int().nonnegative(),
        description: "起始偏移量，0 表示第一条。",
        probeValue: 0,
      },
      {
        name: "size",
        in: "query",
        required: true,
        schema: z.number().int().positive(),
        description: "本次最多返回的帖子数量。",
        probeValue: 2,
      },
    ],
    responses: {
      "200": {
        description: "同一匿名作者在该主题中的帖子列表",
        contentType: "application/json",
        schema: z.array(postSchema),
      },
      default: {
        description: "API 错误码",
        contentType: "application/json",
        schema: errorCodeSchema,
      },
    },
    auth: "required",
    risk: "read-only",
    verificationStatus: "conflicted",
    sources: ["legacy-openapi", "live-probe"],
    deprecated: true,
    description: "旧版前端用于追踪同一匿名作者在主题中的帖子；当前服务不再提供该路由。",
  },
  {
    method: "PUT",
    path: "/post/{postId}/rating",
    operationId: "putPostPostIdRating",
    summary: "提交帖子评分（旧版）",
    tags: ["Post"],
    parameters: [
      {
        name: "postId",
        in: "path",
        required: true,
        schema: z.number().int().positive(),
        description: "需要评分的帖子 ID。",
        probeValue: 124447422,
      },
    ],
    requestBody: {
      required: true,
      contentType: "application/json",
      schema: z
        .object({
          value: z
            .union([z.literal(-1), z.literal(1)])
            .meta({ description: "评分值：1 为正面评分，-1 为负面评分。" }),
          reason: z.string().meta({ description: "评分理由。" }),
        })
        .meta({ description: "旧版自由文本帖子评分请求。" }),
    },
    responses: {
      "200": { description: "帖子评分成功" },
      default: {
        description: "API 错误码",
        contentType: "application/json",
        schema: errorCodeSchema,
      },
    },
    auth: "required",
    risk: "write",
    verificationStatus: "unknown",
    sources: ["legacy-openapi", "live-probe"],
    deprecated: true,
    description: "使用正负评分值和自由文本理由给帖子评分。新客户端应使用 rating-v2 接口。",
  },
  {
    method: "PUT",
    path: "/post/{postId}/rating-v2",
    operationId: "putPostPostIdRatingV2",
    summary: "按预设理由给帖子评分",
    tags: ["Post"],
    parameters: [
      {
        name: "postId",
        in: "path",
        required: true,
        schema: z.number().int().positive(),
        description: "需要评分的帖子 ID。",
        probeValue: 124447422,
      },
    ],
    requestBody: {
      required: true,
      contentType: "application/json",
      schema: postRatingRequestSchema,
    },
    responses: {
      "200": { description: "帖子评分成功" },
      default: {
        description: "API 错误码",
        contentType: "application/json",
        schema: errorCodeSchema,
      },
    },
    auth: "required",
    risk: "write",
    verificationStatus: "unknown",
    sources: ["legacy-openapi", "live-probe"],
    description: "使用评分类型和预设理由 ID 给指定帖子提交正面或负面评分。",
  },
  {
    method: "POST",
    path: "/post/{postId}/operation",
    operationId: "postPostPostIdOperation",
    summary: "执行帖子管理操作",
    tags: ["Post", "Moderation"],
    parameters: [
      {
        name: "postId",
        in: "path",
        required: true,
        schema: z.number().int().positive(),
        description: "作为管理操作依据的帖子 ID。",
        probeValue: 124447422,
      },
    ],
    requestBody: {
      required: true,
      contentType: "application/json",
      schema: postOperationRequestSchema,
    },
    responses: {
      "200": { description: "帖子管理操作成功" },
      default: {
        description: "API 错误码",
        contentType: "application/json",
        schema: errorCodeSchema,
      },
    },
    auth: "required",
    risk: "destructive",
    verificationStatus: "unknown",
    sources: ["legacy-openapi", "live-probe"],
    description: "根据帖子执行财富或声望奖励、扣除，以及对发帖用户实施版面禁言。需要相应管理权限。",
  },
  {
    method: "GET",
    path: "/post/{postId}/awards",
    operationId: "getPostPostIdAwards",
    summary: "获取帖子奖励和处罚记录",
    tags: ["Post"],
    parameters: [
      {
        name: "postId",
        in: "path",
        required: true,
        schema: z.number().int().positive(),
        description: "需要查询奖励和处罚记录的帖子 ID。",
        probeValue: 124447422,
      },
    ],
    responses: {
      "200": {
        description: "成功获取帖子的奖励和处罚记录",
        contentType: "application/json",
        schema: z.array(postAwardSchema),
      },
      default: {
        description: "API 错误码",
        contentType: "application/json",
        schema: errorCodeSchema,
      },
    },
    auth: "anonymous",
    risk: "read-only",
    verificationStatus: "verified-anonymous",
    sources: ["legacy-openapi", "live-probe"],
    description: "返回管理人员对指定帖子执行的财富、声望等奖励或处罚记录。",
  },
  {
    method: "GET",
    path: "/manage/reward-daily-record",
    operationId: "getManageRewardDailyRecord",
    summary: "查询版面每日奖励额度",
    tags: ["Moderation"],
    parameters: [
      {
        name: "boardId",
        in: "query",
        required: true,
        schema: z.number().int().positive(),
        description: "需要查询奖励额度的版面 ID。",
        probeValue: 758,
      },
    ],
    responses: {
      "200": {
        description: "成功获取版面的每日奖励额度使用情况",
        contentType: "application/json",
        schema: postRewardDailyRecordSchema,
      },
      default: {
        description: "API 错误码",
        contentType: "application/json",
        schema: errorCodeSchema,
      },
    },
    auth: "required",
    risk: "read-only",
    verificationStatus: "permission-denied",
    sources: ["legacy-openapi", "live-probe"],
    description: "供版面管理人员查询当天可发放的财富值上限及已发放数量。",
  },
  {
    method: "GET",
    path: "/post/rating-reason",
    operationId: "getPostRatingReason",
    summary: "获取帖子评分理由",
    tags: ["Post"],
    parameters: [
      {
        name: "type",
        in: "query",
        required: true,
        schema: postRatingTypeSchema,
        description: "评分类型：1 为正面评分，2 为负面评分。",
        probeValue: 1,
      },
    ],
    responses: {
      "200": {
        description: "成功获取指定类型的评分理由列表",
        contentType: "application/json",
        schema: z.array(ratingReasonSchema),
      },
    },
    auth: "anonymous",
    risk: "read-only",
    verificationStatus: "verified-anonymous",
    sources: ["legacy-openapi", "live-probe"],
    description: "返回帖子评分时可选择的预设理由，可通过 enabled 判断是否可用。",
  },
  {
    method: "POST",
    path: "/post/topic/{topicId}",
    operationId: "postPostTopicTopicId",
    summary: "回复主题（旧路由）",
    tags: ["Post", "Topic"],
    parameters: [
      {
        name: "topicId",
        in: "path",
        required: true,
        schema: z.number().int().positive(),
        description: "需要回复的主题 ID。",
        probeValue: 6572083,
      },
    ],
    requestBody: {
      required: true,
      contentType: "application/json",
      schema: createPostRequestSchema,
    },
    responses: { "200": { description: "回复发布成功" } },
    auth: "required",
    risk: "write",
    verificationStatus: "unknown",
    sources: ["legacy-openapi", "live-probe"],
    deprecated: true,
    description: "旧版回帖路由。新客户端应使用 POST /topic/{topicId}/post。",
  },
]);
