import { z } from "zod";
import { defineOperations } from "./types.ts";
import {
  createPostRequestSchema,
  errorCodeSchema,
  errorEnvelopeSchema,
  numericIdResponseSchema,
  postSchema,
  reasonRequestSchema,
  recommendedTopicSchema,
  submitVoteRequestSchema,
  topicSchema,
  topicHighlightRequestSchema,
  topicIpGroupSchema,
  topicPagedResultSchema,
  topicTopRequestSchema,
  voteInfoSchema,
} from "../schemas/index.ts";

export const topicOperations = defineOperations([
  {
    method: "GET",
    path: "/topic/{topicId}",
    operationId: "getTopicTopicId",
    summary: "Get topic details",
    tags: ["Topic"],
    parameters: [
      { name: "topicId", in: "path", required: true, schema: z.number(), probeValue: 6572083 },
    ],
    responses: {
      "200": { description: "Topic details", contentType: "application/json", schema: topicSchema },
      default: {
        description: "API 错误码",
        contentType: "application/json",
        schema: errorCodeSchema,
      },
    },
    auth: "required",
    risk: "read-only",
    verificationStatus: "verified-authenticated",
    sources: ["legacy-openapi", "live-probe"],
  },
  {
    method: "DELETE",
    path: "/topic/{topicId}",
    operationId: "deleteTopicTopicId",
    summary: "Delete topic",
    tags: ["Topic", "Moderation"],
    parameters: [
      { name: "topicId", in: "path", required: true, schema: z.number(), probeValue: 6572083 },
    ],
    requestBody: { required: false, contentType: "application/json", schema: reasonRequestSchema },
    responses: {
      "200": { description: "Success" },
      default: {
        description: "API 错误码",
        contentType: "application/json",
        schema: errorCodeSchema,
      },
    },
    auth: "required",
    risk: "destructive",
    verificationStatus: "permission-denied",
    sources: ["legacy-openapi", "live-probe"],
  },
  {
    method: "GET",
    path: "/topic/{topicId}/post",
    operationId: "getTopicTopicIdPost",
    summary: "Get posts in a topic",
    tags: ["Topic", "Post"],
    parameters: [
      { name: "topicId", in: "path", required: true, schema: z.number(), probeValue: 6572083 },
      { name: "from", in: "query", required: true, schema: z.number(), probeValue: 0 },
      { name: "size", in: "query", required: true, schema: z.number(), probeValue: 2 },
    ],
    responses: {
      "200": {
        description: "Post list",
        contentType: "application/json",
        schema: z.array(postSchema),
      },
      default: {
        description: "API 错误码",
        contentType: "application/json",
        schema: errorCodeSchema,
      },
    },
    auth: "required",
    risk: "read-only",
    verificationStatus: "verified-write",
    sources: ["legacy-openapi", "live-probe"],
  },
  {
    method: "POST",
    path: "/topic/{topicId}/post",
    operationId: "postTopicTopicIdPost",
    summary: "Reply to a topic",
    tags: ["Topic", "Post"],
    parameters: [
      { name: "topicId", in: "path", required: true, schema: z.number(), probeValue: 6572083 },
    ],
    requestBody: {
      required: true,
      contentType: "application/json",
      schema: createPostRequestSchema,
    },
    responses: {
      "200": {
        description: "新回复 ID",
        contentType: "application/json",
        schema: numericIdResponseSchema,
      },
      default: {
        description: "API 错误码",
        contentType: "application/json",
        schema: errorCodeSchema,
      },
    },
    auth: "required",
    risk: "write",
    verificationStatus: "verified-write",
    sources: ["legacy-openapi", "live-probe"],
  },
  {
    method: "GET",
    path: "/topic/{topicId}/hot-post",
    operationId: "getTopicTopicIdHotPost",
    summary: "Get hot posts in a topic",
    tags: ["Topic", "Post"],
    parameters: [
      { name: "topicId", in: "path", required: true, schema: z.number(), probeValue: 6572083 },
    ],
    responses: {
      "200": {
        description: "Hot posts",
        contentType: "application/json",
        schema: z.array(postSchema),
      },
      default: {
        description: "API 错误码",
        contentType: "application/json",
        schema: errorCodeSchema,
      },
    },
    auth: "required",
    risk: "read-only",
    verificationStatus: "verified-authenticated",
    sources: ["legacy-openapi", "live-probe"],
  },
  {
    method: "GET",
    path: "/topic/{topicId}/vote",
    operationId: "getTopicTopicIdVote",
    summary: "Get topic vote info",
    tags: ["Topic"],
    parameters: [
      { name: "topicId", in: "path", required: true, schema: z.number(), probeValue: 6572083 },
    ],
    responses: {
      "200": { description: "Vote info", contentType: "application/json", schema: voteInfoSchema },
      default: {
        description: "API 错误码",
        contentType: "application/json",
        schema: errorCodeSchema,
      },
    },
    auth: "required",
    risk: "read-only",
    verificationStatus: "unknown",
    sources: ["legacy-openapi", "live-probe"],
  },
  {
    method: "POST",
    path: "/topic/{topicId}/vote",
    operationId: "postTopicTopicIdVote",
    summary: "Submit vote",
    tags: ["Topic"],
    parameters: [
      { name: "topicId", in: "path", required: true, schema: z.number(), probeValue: 6572083 },
    ],
    requestBody: {
      required: true,
      contentType: "application/json",
      schema: submitVoteRequestSchema,
    },
    responses: {
      "200": { description: "Success" },
      default: {
        description: "API 错误码",
        contentType: "application/json",
        schema: errorCodeSchema,
      },
    },
    auth: "required",
    risk: "write",
    verificationStatus: "unknown",
    sources: ["legacy-openapi", "live-probe"],
  },
  {
    method: "GET",
    path: "/topic/{topicId}/isfavorite",
    operationId: "getTopicTopicIdIsfavorite",
    summary: "Check whether current user has favorited a topic",
    tags: ["Topic", "Me"],
    parameters: [
      { name: "topicId", in: "path", required: true, schema: z.number(), probeValue: 6572083 },
    ],
    responses: {
      "200": {
        description: "Favorite state",
        contentType: "application/json",
        schema: z.boolean(),
      },
      default: {
        description: "API 错误码",
        contentType: "application/json",
        schema: errorCodeSchema,
      },
    },
    auth: "anonymous",
    risk: "account-scoped",
    verificationStatus: "verified-anonymous",
    sources: ["legacy-openapi", "live-probe"],
  },
  {
    method: "GET",
    path: "/topic/{topicId}/event",
    operationId: "getTopicTopicIdEvent",
    summary: "Get topic event records",
    tags: ["Topic", "Moderation"],
    parameters: [
      { name: "topicId", in: "path", required: true, schema: z.number(), probeValue: 6572083 },
      { name: "from", in: "query", required: true, schema: z.number(), probeValue: 0 },
      { name: "size", in: "query", required: true, schema: z.number(), probeValue: 2 },
    ],
    responses: {
      "200": {
        description: "Topic events",
        contentType: "application/json",
        schema: z.union([z.array(z.looseObject({})), errorEnvelopeSchema]),
      },
      default: {
        description: "API 错误码",
        contentType: "application/json",
        schema: errorCodeSchema,
      },
    },
    auth: "anonymous",
    risk: "destructive",
    verificationStatus: "verified-anonymous",
    sources: ["legacy-openapi", "live-probe"],
  },
  {
    method: "GET",
    path: "/topic/{topicId}/look-ip",
    operationId: "getTopicTopicIdLookIp",
    summary: "View IP groups for a topic",
    tags: ["Topic", "Moderation"],
    parameters: [
      { name: "topicId", in: "path", required: true, schema: z.number(), probeValue: 6572083 },
    ],
    responses: {
      "200": {
        description: "IP grouped posts",
        contentType: "application/json",
        schema: z.array(topicIpGroupSchema),
      },
      default: {
        description: "API 错误码",
        contentType: "application/json",
        schema: errorCodeSchema,
      },
    },
    auth: "required",
    risk: "destructive",
    verificationStatus: "permission-denied",
    sources: ["legacy-openapi", "live-probe"],
  },
  {
    method: "PUT",
    path: "/topic/{topicId}/top",
    operationId: "putTopicTopicIdTop",
    summary: "Set topic top state",
    tags: ["Topic", "Moderation"],
    parameters: [
      { name: "topicId", in: "path", required: true, schema: z.number(), probeValue: 6572083 },
    ],
    requestBody: {
      required: false,
      contentType: "application/json",
      schema: topicTopRequestSchema,
    },
    responses: {
      "200": { description: "Success" },
      default: {
        description: "API 错误码",
        contentType: "application/json",
        schema: errorCodeSchema,
      },
    },
    auth: "required",
    risk: "destructive",
    verificationStatus: "unknown",
    sources: ["legacy-openapi", "live-probe"],
  },
  {
    method: "DELETE",
    path: "/topic/{topicId}/top",
    operationId: "deleteTopicTopicIdTop",
    summary: "Remove topic top state",
    tags: ["Topic", "Moderation"],
    parameters: [
      { name: "topicId", in: "path", required: true, schema: z.number(), probeValue: 6572083 },
    ],
    requestBody: { required: false, contentType: "application/json", schema: reasonRequestSchema },
    responses: {
      "200": { description: "Success" },
      default: {
        description: "API 错误码",
        contentType: "application/json",
        schema: errorCodeSchema,
      },
    },
    auth: "required",
    risk: "destructive",
    verificationStatus: "unknown",
    sources: ["legacy-openapi", "live-probe"],
  },
  {
    method: "PUT",
    path: "/topic/{topicId}/lock",
    operationId: "putTopicTopicIdLock",
    summary: "Lock topic",
    tags: ["Topic", "Moderation"],
    parameters: [
      { name: "topicId", in: "path", required: true, schema: z.number(), probeValue: 6572083 },
    ],
    requestBody: {
      required: false,
      contentType: "application/json",
      schema: z.object({ reason: z.string().optional(), value: z.number().optional() }),
    },
    responses: {
      "200": { description: "Success" },
      default: {
        description: "API 错误码",
        contentType: "application/json",
        schema: errorCodeSchema,
      },
    },
    auth: "required",
    risk: "destructive",
    verificationStatus: "unknown",
    sources: ["legacy-openapi", "live-probe"],
  },
  {
    method: "DELETE",
    path: "/topic/{topicId}/lock",
    operationId: "deleteTopicTopicIdLock",
    summary: "Unlock topic",
    tags: ["Topic", "Moderation"],
    parameters: [
      { name: "topicId", in: "path", required: true, schema: z.number(), probeValue: 6572083 },
    ],
    requestBody: { required: false, contentType: "application/json", schema: reasonRequestSchema },
    responses: {
      "200": { description: "Success" },
      default: {
        description: "API 错误码",
        contentType: "application/json",
        schema: errorCodeSchema,
      },
    },
    auth: "required",
    risk: "destructive",
    verificationStatus: "unknown",
    sources: ["legacy-openapi", "live-probe"],
  },
  {
    method: "PUT",
    path: "/topic/{topicId}/best",
    operationId: "putTopicTopicIdBest",
    summary: "Mark topic as best",
    tags: ["Topic", "Moderation"],
    parameters: [
      { name: "topicId", in: "path", required: true, schema: z.number(), probeValue: 6572083 },
    ],
    requestBody: { required: false, contentType: "application/json", schema: reasonRequestSchema },
    responses: {
      "200": { description: "Success" },
      default: {
        description: "API 错误码",
        contentType: "application/json",
        schema: errorCodeSchema,
      },
    },
    auth: "required",
    risk: "destructive",
    verificationStatus: "unknown",
    sources: ["legacy-openapi", "live-probe"],
  },
  {
    method: "DELETE",
    path: "/topic/{topicId}/best",
    operationId: "deleteTopicTopicIdBest",
    summary: "Remove best topic mark",
    tags: ["Topic", "Moderation"],
    parameters: [
      { name: "topicId", in: "path", required: true, schema: z.number(), probeValue: 6572083 },
    ],
    requestBody: { required: false, contentType: "application/json", schema: reasonRequestSchema },
    responses: {
      "200": { description: "Success" },
      default: {
        description: "API 错误码",
        contentType: "application/json",
        schema: errorCodeSchema,
      },
    },
    auth: "required",
    risk: "destructive",
    verificationStatus: "unknown",
    sources: ["legacy-openapi", "live-probe"],
  },
  {
    method: "PUT",
    path: "/topic/{topicId}/not-hot",
    operationId: "putTopicTopicIdNotHot",
    summary: "Disable topic from hot list",
    tags: ["Topic", "Moderation"],
    parameters: [
      { name: "topicId", in: "path", required: true, schema: z.number(), probeValue: 6572083 },
    ],
    requestBody: { required: false, contentType: "application/json", schema: reasonRequestSchema },
    responses: {
      "200": { description: "Success" },
      default: {
        description: "API 错误码",
        contentType: "application/json",
        schema: errorCodeSchema,
      },
    },
    auth: "required",
    risk: "destructive",
    verificationStatus: "unknown",
    sources: ["legacy-openapi", "live-probe"],
  },
  {
    method: "DELETE",
    path: "/topic/{topicId}/not-hot",
    operationId: "deleteTopicTopicIdNotHot",
    summary: "Enable topic for hot list",
    tags: ["Topic", "Moderation"],
    parameters: [
      { name: "topicId", in: "path", required: true, schema: z.number(), probeValue: 6572083 },
    ],
    requestBody: { required: false, contentType: "application/json", schema: reasonRequestSchema },
    responses: {
      "200": { description: "Success" },
      default: {
        description: "API 错误码",
        contentType: "application/json",
        schema: errorCodeSchema,
      },
    },
    auth: "required",
    risk: "destructive",
    verificationStatus: "unknown",
    sources: ["legacy-openapi", "live-probe"],
  },
  {
    method: "PUT",
    path: "/topic/{topicId}/highlight",
    operationId: "putTopicTopicIdHighlight",
    summary: "Set topic highlight style",
    tags: ["Topic", "Moderation"],
    parameters: [
      { name: "topicId", in: "path", required: true, schema: z.number(), probeValue: 6572083 },
    ],
    requestBody: {
      required: false,
      contentType: "application/json",
      schema: topicHighlightRequestSchema,
    },
    responses: {
      "200": { description: "Success" },
      default: {
        description: "API 错误码",
        contentType: "application/json",
        schema: errorCodeSchema,
      },
    },
    auth: "required",
    risk: "destructive",
    verificationStatus: "unknown",
    sources: ["legacy-openapi", "live-probe"],
  },
  {
    method: "PUT",
    path: "/topic/{topicId}/up",
    operationId: "putTopicTopicIdUp",
    summary: "Bump topic",
    tags: ["Topic", "Moderation"],
    parameters: [
      { name: "topicId", in: "path", required: true, schema: z.number(), probeValue: 6572083 },
    ],
    requestBody: { required: false, contentType: "application/json", schema: reasonRequestSchema },
    responses: {
      "200": { description: "Success" },
      default: {
        description: "API 错误码",
        contentType: "application/json",
        schema: errorCodeSchema,
      },
    },
    auth: "required",
    risk: "destructive",
    verificationStatus: "unknown",
    sources: ["legacy-openapi", "live-probe"],
  },
  {
    method: "PUT",
    path: "/topic/{topicId}/moveto/{boardId}",
    operationId: "putTopicTopicIdMovetoBoardId",
    summary: "Move topic to another board",
    tags: ["Topic", "Moderation"],
    parameters: [
      { name: "topicId", in: "path", required: true, schema: z.number(), probeValue: 6572083 },
      { name: "boardId", in: "path", required: true, schema: z.number(), probeValue: 758 },
    ],
    requestBody: { required: false, contentType: "application/json", schema: reasonRequestSchema },
    responses: {
      "200": { description: "Success" },
      default: {
        description: "API 错误码",
        contentType: "application/json",
        schema: errorCodeSchema,
      },
    },
    auth: "required",
    risk: "destructive",
    verificationStatus: "unknown",
    sources: ["legacy-openapi", "live-probe"],
  },
  {
    method: "PUT",
    path: "/topic/multi-lock",
    operationId: "putTopicMultiLock",
    summary: "Lock multiple topics",
    tags: ["Topic", "Moderation"],
    parameters: [
      {
        name: "target",
        in: "query",
        required: false,
        schema: z.string(),
        description: "Placeholder for one or more target topic query parameters.",
      },
    ],
    requestBody: {
      required: true,
      contentType: "application/json",
      schema: z.object({ reason: z.string().optional(), value: z.number().optional() }),
    },
    responses: {
      "200": { description: "Success" },
      default: {
        description: "API 错误码",
        contentType: "application/json",
        schema: errorCodeSchema,
      },
    },
    auth: "required",
    risk: "destructive",
    verificationStatus: "unknown",
    sources: ["legacy-openapi", "live-probe"],
    description:
      "The target topics are passed as query string generated by the frontend; exact parameter names are inferred as backend-specific.",
  },
  {
    method: "PUT",
    path: "/topic/multi-delete",
    operationId: "putTopicMultiDelete",
    summary: "Delete multiple topics",
    tags: ["Topic", "Moderation"],
    parameters: [
      {
        name: "target",
        in: "query",
        required: false,
        schema: z.string(),
        description: "Placeholder for one or more target topic query parameters.",
      },
    ],
    requestBody: { required: true, contentType: "application/json", schema: reasonRequestSchema },
    responses: {
      "200": { description: "Success" },
      default: {
        description: "API 错误码",
        contentType: "application/json",
        schema: errorCodeSchema,
      },
    },
    auth: "required",
    risk: "destructive",
    verificationStatus: "unknown",
    sources: ["legacy-openapi", "live-probe"],
    description:
      "The target topics are passed as query string generated by the frontend; exact parameter names are inferred as backend-specific.",
  },
  {
    method: "GET",
    path: "/topic/toptopics",
    operationId: "getTopicToptopics",
    summary: "Get top topics in a board",
    tags: ["Topic"],
    parameters: [
      { name: "boardid", in: "query", required: true, schema: z.number(), probeValue: 758 },
    ],
    responses: {
      "200": {
        description: "Top topics",
        contentType: "application/json",
        schema: z.array(topicSchema),
      },
      default: {
        description: "API 错误码",
        contentType: "application/json",
        schema: errorCodeSchema,
      },
    },
    auth: "required",
    risk: "read-only",
    verificationStatus: "verified-authenticated",
    sources: ["legacy-openapi", "live-probe"],
  },
  {
    method: "GET",
    path: "/topic/best/board/{boardId}",
    operationId: "getTopicBestBoardBoardId",
    summary: "Get best topics in a board",
    tags: ["Topic", "Board"],
    parameters: [
      { name: "boardId", in: "path", required: true, schema: z.number(), probeValue: 758 },
      { name: "from", in: "query", required: true, schema: z.number(), probeValue: 0 },
      { name: "size", in: "query", required: true, schema: z.number(), probeValue: 2 },
    ],
    responses: {
      "200": {
        description: "Paged topics",
        contentType: "application/json",
        schema: topicPagedResultSchema,
      },
      default: {
        description: "API 错误码",
        contentType: "application/json",
        schema: errorCodeSchema,
      },
    },
    auth: "required",
    risk: "read-only",
    verificationStatus: "verified-authenticated",
    sources: ["legacy-openapi", "live-probe"],
  },
  {
    method: "GET",
    path: "/topic/save/board/{boardId}",
    operationId: "getTopicSaveBoardBoardId",
    summary: "Get saved topics in a board",
    tags: ["Topic", "Board"],
    parameters: [
      { name: "boardId", in: "path", required: true, schema: z.number(), probeValue: 758 },
      { name: "from", in: "query", required: true, schema: z.number(), probeValue: 0 },
      { name: "size", in: "query", required: true, schema: z.number(), probeValue: 2 },
    ],
    responses: {
      "200": {
        description: "Paged topics",
        contentType: "application/json",
        schema: topicPagedResultSchema,
      },
      default: {
        description: "API 错误码",
        contentType: "application/json",
        schema: errorCodeSchema,
      },
    },
    auth: "required",
    risk: "read-only",
    verificationStatus: "verified-authenticated",
    sources: ["legacy-openapi", "live-probe"],
  },
  {
    method: "GET",
    path: "/topic/search",
    operationId: "getTopicSearch",
    summary: "Search topics globally",
    tags: ["Topic"],
    parameters: [
      { name: "keyword", in: "query", required: true, schema: z.string(), probeValue: "测试" },
      { name: "from", in: "query", required: true, schema: z.number(), probeValue: 0 },
      { name: "size", in: "query", required: true, schema: z.number(), probeValue: 2 },
    ],
    responses: {
      "200": {
        description: "Topic search results",
        contentType: "application/json",
        schema: z.array(topicSchema),
      },
      default: {
        description: "API 错误码",
        contentType: "application/json",
        schema: errorCodeSchema,
      },
    },
    auth: "required",
    risk: "read-only",
    verificationStatus: "verified-authenticated",
    sources: ["legacy-openapi", "live-probe"],
  },
  {
    method: "GET",
    path: "/topic/search/board/{boardId}",
    operationId: "getTopicSearchBoardBoardId",
    summary: "Search topics in a board",
    tags: ["Topic", "Board"],
    parameters: [
      { name: "boardId", in: "path", required: true, schema: z.number(), probeValue: 758 },
      { name: "keyword", in: "query", required: true, schema: z.string(), probeValue: "测试" },
      { name: "from", in: "query", required: true, schema: z.number(), probeValue: 0 },
      { name: "size", in: "query", required: true, schema: z.number(), probeValue: 2 },
    ],
    responses: {
      "200": {
        description: "Topic search results",
        contentType: "application/json",
        schema: z.array(topicSchema),
      },
      default: {
        description: "API 错误码",
        contentType: "application/json",
        schema: errorCodeSchema,
      },
    },
    auth: "required",
    risk: "read-only",
    verificationStatus: "verified-authenticated",
    sources: ["legacy-openapi", "live-probe"],
  },
  {
    method: "GET",
    path: "/topic/search/board/{boardId}/tag",
    operationId: "getTopicSearchBoardBoardIdTag",
    summary: "Search board topics by tags",
    tags: ["Topic", "Board"],
    parameters: [
      { name: "boardId", in: "path", required: true, schema: z.number(), probeValue: 758 },
      { name: "tag1", in: "query", required: false, schema: z.number(), probeValue: 1 },
      { name: "tag2", in: "query", required: false, schema: z.number() },
      { name: "from", in: "query", required: true, schema: z.number(), probeValue: 0 },
      { name: "size", in: "query", required: true, schema: z.number(), probeValue: 2 },
    ],
    responses: {
      "200": {
        description: "Paged topics",
        contentType: "application/json",
        schema: topicPagedResultSchema,
      },
      default: {
        description: "API 错误码",
        contentType: "application/json",
        schema: errorCodeSchema,
      },
    },
    auth: "required",
    risk: "read-only",
    verificationStatus: "unknown",
    sources: ["legacy-openapi", "live-probe"],
  },
  {
    method: "GET",
    path: "/topic/new",
    operationId: "getTopicNew",
    summary: "Get newest topics",
    tags: ["Topic"],
    parameters: [
      { name: "from", in: "query", required: true, schema: z.number(), probeValue: 0 },
      { name: "size", in: "query", required: true, schema: z.number(), probeValue: 2 },
    ],
    responses: {
      "200": {
        description: "New topics",
        contentType: "application/json",
        schema: z.array(topicSchema),
      },
      default: {
        description: "API 错误码",
        contentType: "application/json",
        schema: errorCodeSchema,
      },
    },
    auth: "required",
    risk: "read-only",
    verificationStatus: "verified-authenticated",
    sources: ["legacy-openapi", "live-probe"],
  },
  {
    method: "GET",
    path: "/topic/new-media",
    operationId: "getTopicNewMedia",
    summary: "Get newest media topics",
    tags: ["Topic"],
    parameters: [
      { name: "from", in: "query", required: true, schema: z.number(), probeValue: 0 },
      { name: "size", in: "query", required: true, schema: z.number(), probeValue: 2 },
    ],
    responses: {
      "200": {
        description: "New media topics",
        contentType: "application/json",
        schema: z.array(topicSchema),
      },
      default: {
        description: "API 错误码",
        contentType: "application/json",
        schema: errorCodeSchema,
      },
    },
    auth: "required",
    risk: "read-only",
    verificationStatus: "verified-authenticated",
    sources: ["legacy-openapi", "live-probe"],
  },
  {
    method: "GET",
    path: "/topic/random-recommendation",
    operationId: "getTopicRandomRecommendation",
    summary: "Get random recommended topics",
    tags: ["Topic"],
    parameters: [{ name: "size", in: "query", required: true, schema: z.number(), probeValue: 2 }],
    responses: {
      "200": {
        description: "Recommended topic list",
        contentType: "application/json",
        schema: z.array(recommendedTopicSchema),
      },
      default: {
        description: "API 错误码",
        contentType: "application/json",
        schema: errorCodeSchema,
      },
    },
    auth: "required",
    risk: "read-only",
    verificationStatus: "verified-authenticated",
    sources: ["legacy-openapi", "live-probe"],
  },
  {
    method: "GET",
    path: "/topic/random-recent",
    operationId: "getTopicRandomRecent",
    summary: "Get random recent topics",
    tags: ["Topic"],
    parameters: [{ name: "size", in: "query", required: true, schema: z.number(), probeValue: 2 }],
    responses: {
      "200": {
        description: "Topic list",
        contentType: "application/json",
        schema: z.array(topicSchema),
      },
      default: {
        description: "API 错误码",
        contentType: "application/json",
        schema: errorCodeSchema,
      },
    },
    auth: "anonymous",
    risk: "read-only",
    verificationStatus: "verified-anonymous",
    sources: ["legacy-openapi", "live-probe"],
  },
  {
    method: "GET",
    path: "/topic/hot-{type}",
    operationId: "getTopicHotType",
    summary: "Get hot topics by type",
    tags: ["Topic"],
    parameters: [
      {
        name: "type",
        in: "path",
        required: true,
        schema: z.union([z.literal("weekly"), z.literal("monthly"), z.literal("history")]),
        probeValue: "monthly",
      },
    ],
    responses: {
      "200": {
        description: "Hot topics",
        contentType: "application/json",
        schema: z.array(topicSchema),
      },
      default: {
        description: "API 错误码",
        contentType: "application/json",
        schema: errorCodeSchema,
      },
    },
    auth: "anonymous",
    risk: "read-only",
    verificationStatus: "verified-anonymous",
    sources: ["legacy-openapi", "live-probe"],
  },
  {
    method: "GET",
    path: "/topic/basic",
    operationId: "getTopicBasic",
    summary: "Get basic topic info by repeated id query",
    tags: ["Topic"],
    parameters: [
      { name: "id", in: "query", required: true, schema: z.array(z.number()), probeValue: 758 },
    ],
    responses: {
      "200": {
        description: "Basic topics",
        contentType: "application/json",
        schema: z.array(topicSchema),
      },
      default: {
        description: "API 错误码",
        contentType: "application/json",
        schema: errorCodeSchema,
      },
    },
    auth: "anonymous",
    risk: "read-only",
    verificationStatus: "verified-anonymous",
    sources: ["legacy-openapi", "live-probe"],
  },
  {
    method: "GET",
    path: "/topic/me/favorite",
    operationId: "getTopicMeFavorite",
    summary: "Get current user's favorite topics",
    tags: ["Topic", "Me"],
    parameters: [
      { name: "from", in: "query", required: true, schema: z.number(), probeValue: 0 },
      { name: "size", in: "query", required: true, schema: z.number(), probeValue: 2 },
      { name: "order", in: "query", required: false, schema: z.number() },
      { name: "groupid", in: "query", required: false, schema: z.number() },
    ],
    responses: {
      "200": {
        description: "Favorite topics",
        contentType: "application/json",
        schema: z.array(topicSchema),
      },
      default: {
        description: "API 错误码",
        contentType: "application/json",
        schema: errorCodeSchema,
      },
    },
    auth: "required",
    risk: "read-only",
    verificationStatus: "verified-authenticated",
    sources: ["legacy-openapi", "live-probe"],
  },
  {
    method: "GET",
    path: "/topic/me/search-favorite",
    operationId: "getTopicMeSearchFavorite",
    summary: "Search current user's favorite topics",
    tags: ["Topic", "Me"],
    parameters: [
      { name: "keyword", in: "query", required: true, schema: z.string(), probeValue: "测试" },
      { name: "from", in: "query", required: true, schema: z.number(), probeValue: 0 },
      { name: "size", in: "query", required: true, schema: z.number(), probeValue: 2 },
    ],
    responses: {
      "200": {
        description: "Favorite topic search results",
        contentType: "application/json",
        schema: z.array(topicSchema),
      },
      default: {
        description: "API 错误码",
        contentType: "application/json",
        schema: errorCodeSchema,
      },
    },
    auth: "required",
    risk: "read-only",
    verificationStatus: "verified-authenticated",
    sources: ["legacy-openapi", "live-probe"],
  },
]);
