import { z } from "zod";
import { defineOperations } from "./types.ts";
import {
  basicTopicSchema,
  createPostRequestSchema,
  errorCodeSchema,
  numericIdResponseSchema,
  postSchema,
  reasonRequestSchema,
  recommendedTopicSchema,
  submitVoteRequestSchema,
  topicEventPageSchema,
  topicHighlightRequestSchema,
  topicIpGroupSchema,
  topicLockRequestSchema,
  topicPagedResultSchema,
  topicSchema,
  topicTopRequestSchema,
  voteInfoSchema,
} from "../schemas/index.ts";

const topicIdParameter = {
  name: "topicId",
  in: "path",
  required: true,
  schema: z.number().int().positive(),
  description: "主题 ID。",
  probeValue: 6572083,
} as const;

const voteTopicIdParameter = {
  ...topicIdParameter,
  description: "投票主题 ID。",
  probeValue: 6583126,
} as const;

const boardIdParameter = {
  name: "boardId",
  in: "path",
  required: true,
  schema: z.number().int().positive(),
  description: "版面 ID。",
  probeValue: 758,
} as const;

const fromParameter = {
  name: "from",
  in: "query",
  required: true,
  schema: z.number().int().nonnegative(),
  description: "从第几条记录开始获取，0 表示第一条。",
  probeValue: 0,
} as const;

const sizeParameter = {
  name: "size",
  in: "query",
  required: true,
  schema: z.number().int().positive(),
  description: "本次最多返回的记录数量。",
  probeValue: 2,
} as const;

const defaultErrorResponse = {
  description: "API 错误码",
  contentType: "application/json",
  schema: errorCodeSchema,
} as const;

export const topicOperations = defineOperations([
  {
    method: "GET",
    path: "/topic/{topicId}",
    operationId: "getTopicTopicId",
    summary: "获取主题详情",
    tags: ["Topic"],
    parameters: [topicIdParameter],
    responses: {
      "200": {
        description: "主题的标题、作者、状态、统计和展示信息",
        contentType: "application/json",
        schema: topicSchema,
      },
      default: defaultErrorResponse,
    },
    auth: "required",
    risk: "read-only",
    verificationStatus: "verified-authenticated",
    sources: ["legacy-openapi", "live-probe"],
    description:
      "返回指定主题的概要和详情状态，包括作者、版面、回复统计、标签、置顶与精华状态、媒体摘要和当前用户相关权限。",
  },
  {
    method: "DELETE",
    path: "/topic/{topicId}",
    operationId: "deleteTopicTopicId",
    summary: "删除主题",
    tags: ["Topic", "Moderation"],
    parameters: [topicIdParameter],
    requestBody: { required: false, contentType: "application/json", schema: reasonRequestSchema },
    responses: {
      "200": { description: "主题删除请求已处理" },
      default: defaultErrorResponse,
    },
    auth: "required",
    risk: "destructive",
    verificationStatus: "permission-denied",
    sources: ["legacy-openapi", "live-probe"],
    description: "删除指定主题及其回复。该操作需要主题管理权限。",
  },
  {
    method: "GET",
    path: "/topic/{topicId}/post",
    operationId: "getTopicTopicIdPost",
    summary: "获取主题回复",
    tags: ["Topic", "Post"],
    parameters: [topicIdParameter, fromParameter, sizeParameter],
    responses: {
      "200": {
        description: "按楼层顺序返回的主题帖子列表",
        contentType: "application/json",
        schema: z.array(postSchema),
      },
      default: defaultErrorResponse,
    },
    auth: "required",
    risk: "read-only",
    verificationStatus: "verified-authenticated",
    sources: ["legacy-openapi", "live-probe"],
    description: "分页获取指定主题中的主楼和回复。from 按帖子记录位置计算。",
  },
  {
    method: "POST",
    path: "/topic/{topicId}/post",
    operationId: "postTopicTopicIdPost",
    summary: "回复主题",
    tags: ["Topic", "Post"],
    parameters: [topicIdParameter],
    requestBody: {
      required: true,
      contentType: "application/json",
      schema: createPostRequestSchema,
    },
    responses: {
      "200": {
        description: "新回复的帖子 ID",
        contentType: "application/json",
        schema: numericIdResponseSchema,
      },
      default: defaultErrorResponse,
    },
    auth: "required",
    risk: "write",
    verificationStatus: "verified-write",
    sources: ["legacy-openapi", "live-probe"],
    description: "在指定主题中发表回复，也可通过 parentId 回复某一楼层。",
  },
  {
    method: "GET",
    path: "/topic/{topicId}/hot-post",
    operationId: "getTopicTopicIdHotPost",
    summary: "获取主题热门回复",
    tags: ["Topic", "Post"],
    parameters: [topicIdParameter],
    responses: {
      "200": {
        description: "主题中的热门帖子列表",
        contentType: "application/json",
        schema: z.array(postSchema),
      },
      default: defaultErrorResponse,
    },
    auth: "required",
    risk: "read-only",
    verificationStatus: "verified-authenticated",
    sources: ["legacy-openapi", "live-probe"],
    description: "返回指定主题中由服务端判定为热门的回复。",
  },
  {
    method: "GET",
    path: "/topic/{topicId}/vote",
    operationId: "getTopicTopicIdVote",
    summary: "获取主题投票信息",
    tags: ["Topic"],
    parameters: [voteTopicIdParameter],
    responses: {
      "200": {
        description: "投票选项、结果、截止时间和当前用户投票状态",
        contentType: "application/json",
        schema: voteInfoSchema,
      },
      default: defaultErrorResponse,
    },
    auth: "required",
    risk: "read-only",
    verificationStatus: "verified-authenticated",
    sources: ["legacy-openapi", "live-probe"],
    description:
      "返回投票主题的选项、票数、有效期以及当前用户能否投票。投票设置可能限制结果可见性。",
  },
  {
    method: "POST",
    path: "/topic/{topicId}/vote",
    operationId: "postTopicTopicIdVote",
    summary: "提交主题投票",
    tags: ["Topic"],
    parameters: [voteTopicIdParameter],
    requestBody: {
      required: true,
      contentType: "application/json",
      schema: submitVoteRequestSchema,
    },
    responses: {
      "200": { description: "投票提交请求已处理" },
      default: defaultErrorResponse,
    },
    auth: "required",
    risk: "write",
    verificationStatus: "verified-write",
    sources: ["legacy-openapi", "live-probe"],
    description: "为指定投票主题提交当前用户选择的一个或多个选项。",
  },
  {
    method: "GET",
    path: "/topic/{topicId}/isfavorite",
    operationId: "getTopicTopicIdIsfavorite",
    summary: "查询主题收藏状态",
    tags: ["Topic", "Me"],
    parameters: [topicIdParameter],
    responses: {
      "200": {
        description: "当前用户是否已收藏该主题",
        contentType: "application/json",
        schema: z.boolean().meta({ description: "当前用户是否已收藏该主题。" }),
      },
      default: defaultErrorResponse,
    },
    auth: "anonymous",
    risk: "account-scoped",
    verificationStatus: "verified-anonymous",
    sources: ["legacy-openapi", "live-probe"],
    description: "查询指定主题的收藏状态。携带登录凭据时返回当前用户的真实状态。",
  },
  {
    method: "GET",
    path: "/topic/{topicId}/event",
    operationId: "getTopicTopicIdEvent",
    summary: "获取主题操作记录",
    tags: ["Topic", "Moderation"],
    parameters: [topicIdParameter, fromParameter, sizeParameter],
    responses: {
      "200": {
        description: "主题管理操作记录的分页结果",
        contentType: "application/json",
        schema: topicEventPageSchema,
      },
      default: defaultErrorResponse,
    },
    auth: "anonymous",
    risk: "read-only",
    verificationStatus: "verified-anonymous",
    sources: ["legacy-openapi", "live-probe"],
    description: "分页返回指定主题的管理操作记录。具体可见内容由主题状态和用户权限决定。",
  },
  {
    method: "GET",
    path: "/topic/{topicId}/look-ip",
    operationId: "getTopicTopicIdLookIp",
    summary: "按 IP 查看主题回复",
    tags: ["Topic", "Moderation"],
    parameters: [topicIdParameter],
    responses: {
      "200": {
        description: "按 IP 地址分组的主题回复",
        contentType: "application/json",
        schema: z.array(topicIpGroupSchema),
      },
      default: defaultErrorResponse,
    },
    auth: "required",
    risk: "read-only",
    verificationStatus: "permission-denied",
    sources: ["legacy-openapi", "live-probe"],
    description: "按发布 IP 对指定主题中的回复进行分组。该接口需要相应的版务权限。",
  },
  {
    method: "PUT",
    path: "/topic/{topicId}/top",
    operationId: "putTopicTopicIdTop",
    summary: "设置主题置顶",
    tags: ["Topic", "Moderation"],
    parameters: [topicIdParameter],
    requestBody: {
      required: false,
      contentType: "application/json",
      schema: topicTopRequestSchema,
    },
    responses: {
      "200": { description: "主题置顶设置请求已处理" },
      default: defaultErrorResponse,
    },
    auth: "required",
    risk: "destructive",
    verificationStatus: "unknown",
    sources: ["legacy-openapi", "live-probe"],
    description: "将指定主题设置为版面置顶或全站置顶，并可指定持续天数和操作原因。",
  },
  {
    method: "DELETE",
    path: "/topic/{topicId}/top",
    operationId: "deleteTopicTopicIdTop",
    summary: "取消主题置顶",
    tags: ["Topic", "Moderation"],
    parameters: [topicIdParameter],
    requestBody: { required: false, contentType: "application/json", schema: reasonRequestSchema },
    responses: {
      "200": { description: "取消主题置顶请求已处理" },
      default: defaultErrorResponse,
    },
    auth: "required",
    risk: "destructive",
    verificationStatus: "unknown",
    sources: ["legacy-openapi", "live-probe"],
    description: "移除指定主题的置顶状态。",
  },
  {
    method: "PUT",
    path: "/topic/{topicId}/lock",
    operationId: "putTopicTopicIdLock",
    summary: "锁定主题",
    tags: ["Topic", "Moderation"],
    parameters: [topicIdParameter],
    requestBody: {
      required: false,
      contentType: "application/json",
      schema: topicLockRequestSchema,
    },
    responses: {
      "200": { description: "主题锁定请求已处理" },
      default: defaultErrorResponse,
    },
    auth: "required",
    risk: "destructive",
    verificationStatus: "unknown",
    sources: ["legacy-openapi", "live-probe"],
    description: "锁定指定主题，使其不能继续回复，并可指定锁定天数和原因。",
  },
  {
    method: "DELETE",
    path: "/topic/{topicId}/lock",
    operationId: "deleteTopicTopicIdLock",
    summary: "解除主题锁定",
    tags: ["Topic", "Moderation"],
    parameters: [topicIdParameter],
    requestBody: { required: false, contentType: "application/json", schema: reasonRequestSchema },
    responses: {
      "200": { description: "解除主题锁定请求已处理" },
      default: defaultErrorResponse,
    },
    auth: "required",
    risk: "destructive",
    verificationStatus: "unknown",
    sources: ["legacy-openapi", "live-probe"],
    description: "解除指定主题的锁定状态，允许用户继续回复。",
  },
  {
    method: "PUT",
    path: "/topic/{topicId}/best",
    operationId: "putTopicTopicIdBest",
    summary: "将主题设为精华",
    tags: ["Topic", "Moderation"],
    parameters: [topicIdParameter],
    requestBody: { required: false, contentType: "application/json", schema: reasonRequestSchema },
    responses: {
      "200": { description: "主题加精请求已处理" },
      default: defaultErrorResponse,
    },
    auth: "required",
    risk: "destructive",
    verificationStatus: "unknown",
    sources: ["legacy-openapi", "live-probe"],
    description: "将指定主题标记为精华主题。",
  },
  {
    method: "DELETE",
    path: "/topic/{topicId}/best",
    operationId: "deleteTopicTopicIdBest",
    summary: "取消主题精华",
    tags: ["Topic", "Moderation"],
    parameters: [topicIdParameter],
    requestBody: { required: false, contentType: "application/json", schema: reasonRequestSchema },
    responses: {
      "200": { description: "取消主题精华请求已处理" },
      default: defaultErrorResponse,
    },
    auth: "required",
    risk: "destructive",
    verificationStatus: "unknown",
    sources: ["legacy-openapi", "live-probe"],
    description: "移除指定主题的精华标记。",
  },
  {
    method: "PUT",
    path: "/topic/{topicId}/not-hot",
    operationId: "putTopicTopicIdNotHot",
    summary: "禁止主题进入热门列表",
    tags: ["Topic", "Moderation"],
    parameters: [topicIdParameter],
    requestBody: { required: false, contentType: "application/json", schema: reasonRequestSchema },
    responses: {
      "200": { description: "热门列表限制请求已处理" },
      default: defaultErrorResponse,
    },
    auth: "required",
    risk: "destructive",
    verificationStatus: "unknown",
    sources: ["legacy-openapi", "live-probe"],
    description: "设置指定主题不参与热门主题列表的计算和展示。",
  },
  {
    method: "DELETE",
    path: "/topic/{topicId}/not-hot",
    operationId: "deleteTopicTopicIdNotHot",
    summary: "恢复主题进入热门列表",
    tags: ["Topic", "Moderation"],
    parameters: [topicIdParameter],
    requestBody: { required: false, contentType: "application/json", schema: reasonRequestSchema },
    responses: {
      "200": { description: "取消热门列表限制请求已处理" },
      default: defaultErrorResponse,
    },
    auth: "required",
    risk: "destructive",
    verificationStatus: "unknown",
    sources: ["legacy-openapi", "live-probe"],
    description: "取消指定主题的热门列表限制，使其重新参与热门主题计算。",
  },
  {
    method: "PUT",
    path: "/topic/{topicId}/highlight",
    operationId: "putTopicTopicIdHighlight",
    summary: "设置主题标题高亮",
    tags: ["Topic", "Moderation"],
    parameters: [topicIdParameter],
    requestBody: {
      required: false,
      contentType: "application/json",
      schema: topicHighlightRequestSchema,
    },
    responses: {
      "200": { description: "主题高亮设置请求已处理" },
      default: defaultErrorResponse,
    },
    auth: "required",
    risk: "destructive",
    verificationStatus: "unknown",
    sources: ["legacy-openapi", "live-probe"],
    description: "设置指定主题标题的粗体、斜体和颜色样式，并可指定持续天数。",
  },
  {
    method: "PUT",
    path: "/topic/{topicId}/up",
    operationId: "putTopicTopicIdUp",
    summary: "提升主题排序位置",
    tags: ["Topic", "Moderation"],
    parameters: [topicIdParameter],
    requestBody: { required: false, contentType: "application/json", schema: reasonRequestSchema },
    responses: {
      "200": { description: "主题提升请求已处理" },
      default: defaultErrorResponse,
    },
    auth: "required",
    risk: "destructive",
    verificationStatus: "unknown",
    sources: ["legacy-openapi", "live-probe"],
    description: "提升指定主题在版面主题列表中的排序位置。",
  },
  {
    method: "PUT",
    path: "/topic/{topicId}/moveto/{boardId}",
    operationId: "putTopicTopicIdMovetoBoardId",
    summary: "移动主题到其他版面",
    tags: ["Topic", "Moderation"],
    parameters: [topicIdParameter, boardIdParameter],
    requestBody: { required: false, contentType: "application/json", schema: reasonRequestSchema },
    responses: {
      "200": { description: "主题移动请求已处理" },
      default: defaultErrorResponse,
    },
    auth: "required",
    risk: "destructive",
    verificationStatus: "unknown",
    sources: ["legacy-openapi", "live-probe"],
    description: "将指定主题及其回复移动到目标版面。",
  },
  {
    method: "PUT",
    path: "/topic/multi-lock",
    operationId: "putTopicMultiLock",
    summary: "批量锁定主题",
    tags: ["Topic", "Moderation"],
    parameters: [
      {
        name: "id",
        in: "query",
        required: true,
        schema: z.array(z.number().int().positive()),
        description: "需要锁定的主题 ID，可重复传入该查询参数。",
        probeValue: [6572083],
      },
    ],
    requestBody: {
      required: true,
      contentType: "application/json",
      schema: topicLockRequestSchema,
    },
    responses: {
      "200": { description: "批量锁定主题请求已处理" },
      default: defaultErrorResponse,
    },
    auth: "required",
    risk: "destructive",
    verificationStatus: "unknown",
    sources: ["legacy-openapi", "live-probe"],
    description: "通过重复的 id 查询参数一次锁定多个主题。",
  },
  {
    method: "PUT",
    path: "/topic/multi-delete",
    operationId: "putTopicMultiDelete",
    summary: "批量删除主题",
    tags: ["Topic", "Moderation"],
    parameters: [
      {
        name: "id",
        in: "query",
        required: true,
        schema: z.array(z.number().int().positive()),
        description: "需要删除的主题 ID，可重复传入该查询参数。",
        probeValue: [6572083],
      },
    ],
    requestBody: { required: true, contentType: "application/json", schema: reasonRequestSchema },
    responses: {
      "200": { description: "批量删除主题请求已处理" },
      default: defaultErrorResponse,
    },
    auth: "required",
    risk: "destructive",
    verificationStatus: "unknown",
    sources: ["legacy-openapi", "live-probe"],
    description: "通过重复的 id 查询参数一次删除多个主题及其回复。",
  },
  {
    method: "GET",
    path: "/topic/toptopics",
    operationId: "getTopicToptopics",
    summary: "获取版面置顶主题",
    tags: ["Topic"],
    parameters: [
      {
        name: "boardid",
        in: "query",
        required: true,
        schema: z.number().int().positive(),
        description: "版面 ID。",
        probeValue: 758,
      },
    ],
    responses: {
      "200": {
        description: "指定版面需要优先展示的置顶主题",
        contentType: "application/json",
        schema: z.array(topicSchema),
      },
      default: defaultErrorResponse,
    },
    auth: "required",
    risk: "read-only",
    verificationStatus: "verified-authenticated",
    sources: ["legacy-openapi", "live-probe"],
    description: "返回指定版面的置顶主题，用于与普通主题列表分开展示。",
  },
  {
    method: "GET",
    path: "/topic/best/board/{boardId}",
    operationId: "getTopicBestBoardBoardId",
    summary: "获取版面精华主题",
    tags: ["Topic", "Board"],
    parameters: [boardIdParameter, fromParameter, sizeParameter],
    responses: {
      "200": {
        description: "指定版面的精华主题分页结果",
        contentType: "application/json",
        schema: topicPagedResultSchema,
      },
      default: defaultErrorResponse,
    },
    auth: "required",
    risk: "read-only",
    verificationStatus: "verified-authenticated",
    sources: ["legacy-openapi", "live-probe"],
    description: "分页返回指定版面中被标记为精华的主题。",
  },
  {
    method: "GET",
    path: "/topic/save/board/{boardId}",
    operationId: "getTopicSaveBoardBoardId",
    summary: "获取版面保存主题",
    tags: ["Topic", "Board"],
    parameters: [boardIdParameter, fromParameter, sizeParameter],
    responses: {
      "200": {
        description: "指定版面的保存主题分页结果",
        contentType: "application/json",
        schema: topicPagedResultSchema,
      },
      default: defaultErrorResponse,
    },
    auth: "required",
    risk: "read-only",
    verificationStatus: "verified-authenticated",
    sources: ["legacy-openapi", "live-probe"],
    description: "分页返回指定版面中处于“保存”状态的主题；该状态的具体管理规则尚未确认。",
  },
  {
    method: "GET",
    path: "/topic/search",
    operationId: "getTopicSearch",
    summary: "全站搜索主题",
    tags: ["Topic"],
    parameters: [
      {
        name: "keyword",
        in: "query",
        required: true,
        schema: z.string().min(1),
        description: "主题搜索关键词。",
        probeValue: "测试",
      },
      fromParameter,
      sizeParameter,
    ],
    responses: {
      "200": {
        description: "全站主题搜索结果",
        contentType: "application/json",
        schema: z.array(topicSchema),
      },
      default: defaultErrorResponse,
    },
    auth: "required",
    risk: "read-only",
    verificationStatus: "verified-authenticated",
    sources: ["legacy-openapi", "live-probe"],
    description: "按关键词在全站范围搜索主题标题，并分页返回匹配主题。",
  },
  {
    method: "GET",
    path: "/topic/search/board/{boardId}",
    operationId: "getTopicSearchBoardBoardId",
    summary: "搜索版面主题",
    tags: ["Topic", "Board"],
    parameters: [
      boardIdParameter,
      {
        name: "keyword",
        in: "query",
        required: true,
        schema: z.string().min(1),
        description: "主题搜索关键词。",
        probeValue: "测试",
      },
      fromParameter,
      sizeParameter,
    ],
    responses: {
      "200": {
        description: "指定版面中的主题搜索结果",
        contentType: "application/json",
        schema: z.array(topicSchema),
      },
      default: defaultErrorResponse,
    },
    auth: "required",
    risk: "read-only",
    verificationStatus: "verified-authenticated",
    sources: ["legacy-openapi", "live-probe"],
    description: "按关键词搜索指定版面的主题标题，并分页返回匹配主题。",
  },
  {
    method: "GET",
    path: "/topic/search/board/{boardId}/tag",
    operationId: "getTopicSearchBoardBoardIdTag",
    summary: "按标签筛选版面主题",
    tags: ["Topic", "Board"],
    parameters: [
      boardIdParameter,
      {
        name: "tag1",
        in: "query",
        required: false,
        schema: z.number().int().positive(),
        description: "第一层标签 ID；tag1 和 tag2 至少提供一个。",
        probeValue: 1,
      },
      {
        name: "tag2",
        in: "query",
        required: false,
        schema: z.number().int().positive(),
        description: "第二层标签 ID；tag1 和 tag2 至少提供一个。",
      },
      fromParameter,
      sizeParameter,
    ],
    responses: {
      "200": {
        description: "符合标签条件的主题分页结果",
        contentType: "application/json",
        schema: topicPagedResultSchema,
      },
      default: defaultErrorResponse,
    },
    auth: "required",
    risk: "read-only",
    verificationStatus: "verified-authenticated",
    sources: ["legacy-openapi", "live-probe"],
    description: "按一层或两层标签筛选指定版面的主题。tag1 和 tag2 至少需要提供一个。",
  },
  {
    method: "GET",
    path: "/topic/new",
    operationId: "getTopicNew",
    summary: "获取最新主题",
    tags: ["Topic"],
    parameters: [fromParameter, sizeParameter],
    responses: {
      "200": {
        description: "按发布时间或更新时间排列的最新主题",
        contentType: "application/json",
        schema: z.array(topicSchema),
      },
      default: defaultErrorResponse,
    },
    auth: "required",
    risk: "read-only",
    verificationStatus: "verified-authenticated",
    sources: ["legacy-openapi", "live-probe"],
    description: "分页返回全站最新主题，供经典列表和卡片列表使用。具体排序规则由服务端决定。",
  },
  {
    method: "GET",
    path: "/topic/new-media",
    operationId: "getTopicNewMedia",
    summary: "获取最新媒体主题",
    tags: ["Topic"],
    parameters: [fromParameter, sizeParameter],
    responses: {
      "200": {
        description: "包含图片、音视频等媒体摘要的最新主题",
        contentType: "application/json",
        schema: z.array(topicSchema),
      },
      default: defaultErrorResponse,
    },
    auth: "required",
    risk: "read-only",
    verificationStatus: "verified-authenticated",
    sources: ["legacy-openapi", "live-probe"],
    description: "分页返回适合媒体卡片展示的最新主题，mediaContent 中可能包含缩略图或音视频信息。",
  },
  {
    method: "GET",
    path: "/topic/random-recommendation",
    operationId: "getTopicRandomRecommendation",
    summary: "获取随机推荐主题",
    tags: ["Topic"],
    parameters: [sizeParameter],
    responses: {
      "200": {
        description: "推荐主题及正文摘要列表",
        contentType: "application/json",
        schema: z.array(recommendedTopicSchema),
      },
      default: defaultErrorResponse,
    },
    auth: "required",
    risk: "read-only",
    verificationStatus: "verified-authenticated",
    sources: ["legacy-openapi", "live-probe"],
    description: "按照服务端推荐策略随机返回指定数量的主题，并附带正文摘要。",
  },
  {
    method: "GET",
    path: "/topic/random-recent",
    operationId: "getTopicRandomRecent",
    summary: "获取随机近期主题",
    tags: ["Topic"],
    parameters: [sizeParameter],
    responses: {
      "200": {
        description: "随机选取的近期主题列表",
        contentType: "application/json",
        schema: z.array(topicSchema),
      },
      default: defaultErrorResponse,
    },
    auth: "anonymous",
    risk: "read-only",
    verificationStatus: "verified-anonymous",
    sources: ["legacy-openapi", "live-probe"],
    description: "从近期主题中随机返回指定数量的主题。",
  },
  {
    method: "GET",
    path: "/topic/hot-{type}",
    operationId: "getTopicHotType",
    summary: "获取热门主题",
    tags: ["Topic"],
    parameters: [
      {
        name: "type",
        in: "path",
        required: true,
        schema: z.union([z.literal("weekly"), z.literal("monthly"), z.literal("history")]),
        description: "热门统计周期：weekly 为周榜，monthly 为月榜，history 为历史榜。",
        probeValue: "monthly",
      },
    ],
    responses: {
      "200": {
        description: "指定统计周期的热门主题列表",
        contentType: "application/json",
        schema: z.array(topicSchema),
      },
      default: defaultErrorResponse,
    },
    auth: "anonymous",
    risk: "read-only",
    verificationStatus: "verified-anonymous",
    sources: ["legacy-openapi", "live-probe"],
    description: "返回周榜、月榜或历史榜中的热门主题。",
  },
  {
    method: "GET",
    path: "/topic/basic",
    operationId: "getTopicBasic",
    summary: "批量获取主题概要",
    tags: ["Topic"],
    parameters: [
      {
        name: "id",
        in: "query",
        required: true,
        schema: z.array(z.number().int().positive()),
        description: "主题 ID，可重复传入该查询参数。",
        probeValue: [6572083],
      },
    ],
    responses: {
      "200": {
        description: "与给定 ID 对应的主题概要列表",
        contentType: "application/json",
        schema: z.array(basicTopicSchema),
      },
      default: defaultErrorResponse,
    },
    auth: "anonymous",
    risk: "read-only",
    verificationStatus: "verified-anonymous",
    sources: ["legacy-openapi", "live-probe"],
    description: "通过重复的 id 查询参数批量获取主题概要，常用于为帖子或通知补充主题信息。",
  },
  {
    method: "GET",
    path: "/topic/me/favorite",
    operationId: "getTopicMeFavorite",
    summary: "获取当前用户收藏的主题",
    tags: ["Topic", "Me"],
    parameters: [
      fromParameter,
      sizeParameter,
      {
        name: "order",
        in: "query",
        required: false,
        schema: z.union([z.literal(0), z.literal(1), z.literal(2)]),
        description: "排序方式：0 按发帖时间，1 按最后回复时间，2 按收藏顺序。",
      },
      {
        name: "groupid",
        in: "query",
        required: false,
        schema: z.number().int().nonnegative(),
        description: "收藏夹 ID；省略时由服务端选择默认收藏范围。",
      },
    ],
    responses: {
      "200": {
        description: "当前用户收藏的主题列表",
        contentType: "application/json",
        schema: z.array(topicSchema),
      },
      default: defaultErrorResponse,
    },
    auth: "required",
    risk: "read-only",
    verificationStatus: "verified-authenticated",
    sources: ["legacy-openapi", "live-probe"],
    description: "分页返回当前用户收藏的主题，可按收藏夹筛选并选择排序方式。",
  },
  {
    method: "GET",
    path: "/topic/me/search-favorite",
    operationId: "getTopicMeSearchFavorite",
    summary: "搜索当前用户收藏的主题",
    tags: ["Topic", "Me"],
    parameters: [
      {
        name: "keyword",
        in: "query",
        required: true,
        schema: z.string().min(1),
        description: "收藏主题搜索关键词。",
        probeValue: "测试",
      },
      fromParameter,
      sizeParameter,
    ],
    responses: {
      "200": {
        description: "当前用户收藏主题中的搜索结果",
        contentType: "application/json",
        schema: z.array(topicSchema),
      },
      default: defaultErrorResponse,
    },
    auth: "required",
    risk: "read-only",
    verificationStatus: "verified-authenticated",
    sources: ["legacy-openapi", "live-probe"],
    description: "按关键词搜索当前用户收藏的主题，并分页返回匹配结果。",
  },
]);
