import { z } from "zod";
import { defineOperations } from "./types.ts";
import {
  basicUserSchema,
  errorCodeSchema,
  topicSchema,
  userSchema,
  userOperationRequestSchema,
} from "../schemas/index.ts";

export const userOperations = defineOperations([
  {
    method: "GET",
    path: "/user/{id}",
    operationId: "getUserId",
    summary: "Get user details by id",
    tags: ["User"],
    parameters: [{ name: "id", in: "path", required: true, schema: z.number(), probeValue: 758 }],
    responses: {
      "200": { description: "User details", contentType: "application/json", schema: userSchema },
      default: {
        description: "API 错误码",
        contentType: "application/json",
        schema: errorCodeSchema,
      },
    },
    auth: "required",
    risk: "read-only",
    verificationStatus: "unknown",
    sources: ["legacy-openapi", "live-probe"],
  },
  {
    method: "GET",
    path: "/user/name/{userName}",
    operationId: "getUserNameUserName",
    summary: "Get user details by username",
    tags: ["User"],
    parameters: [
      { name: "userName", in: "path", required: true, schema: z.string(), probeValue: "shellRain" },
    ],
    responses: {
      "200": { description: "User details", contentType: "application/json", schema: userSchema },
      default: {
        description: "API 错误码",
        contentType: "application/json",
        schema: errorCodeSchema,
      },
    },
    auth: "anonymous",
    risk: "read-only",
    verificationStatus: "verified-anonymous",
    sources: ["legacy-openapi", "live-probe"],
  },
  {
    method: "GET",
    path: "/user",
    operationId: "getUser",
    summary: "Get users by repeated id query",
    tags: ["User"],
    parameters: [
      { name: "id", in: "query", required: true, schema: z.array(z.number()), probeValue: 758 },
    ],
    responses: {
      "200": { description: "Users", contentType: "application/json", schema: z.array(userSchema) },
      default: {
        description: "API 错误码",
        contentType: "application/json",
        schema: errorCodeSchema,
      },
    },
    auth: "anonymous",
    risk: "read-only",
    verificationStatus: "verified-anonymous",
    sources: ["legacy-openapi", "live-probe"],
  },
  {
    method: "GET",
    path: "/user/name",
    operationId: "getUserName",
    summary: "Get users by repeated username query",
    tags: ["User"],
    parameters: [
      {
        name: "name",
        in: "query",
        required: true,
        schema: z.array(z.string()),
        probeValue: "shellRain",
      },
    ],
    responses: {
      "200": { description: "Users", contentType: "application/json", schema: z.array(userSchema) },
      default: {
        description: "API 错误码",
        contentType: "application/json",
        schema: errorCodeSchema,
      },
    },
    auth: "anonymous",
    risk: "read-only",
    verificationStatus: "verified-anonymous",
    sources: ["legacy-openapi", "live-probe"],
  },
  {
    method: "GET",
    path: "/user/basic",
    operationId: "getUserBasic",
    summary: "Get basic users by repeated id query",
    tags: ["User"],
    parameters: [
      { name: "id", in: "query", required: true, schema: z.array(z.number()), probeValue: 758 },
    ],
    responses: {
      "200": {
        description: "Basic users",
        contentType: "application/json",
        schema: z.array(basicUserSchema),
      },
      default: {
        description: "API 错误码",
        contentType: "application/json",
        schema: errorCodeSchema,
      },
    },
    auth: "anonymous",
    risk: "read-only",
    verificationStatus: "verified-anonymous",
    sources: ["legacy-openapi", "live-probe"],
  },
  {
    method: "GET",
    path: "/user/basic/{id}",
    operationId: "getUserBasicId",
    summary: "Get basic user by id",
    tags: ["User"],
    parameters: [{ name: "id", in: "path", required: true, schema: z.number(), probeValue: 758 }],
    responses: {
      "200": {
        description: "Basic user",
        contentType: "application/json",
        schema: basicUserSchema,
      },
      default: {
        description: "API 错误码",
        contentType: "application/json",
        schema: errorCodeSchema,
      },
    },
    auth: "required",
    risk: "read-only",
    verificationStatus: "unknown",
    sources: ["legacy-openapi", "live-probe"],
  },
  {
    method: "GET",
    path: "/user/{id}/recent-topic",
    operationId: "getUserIdRecentTopic",
    summary: "Get a user's recent topics",
    tags: ["User", "Topic"],
    parameters: [
      { name: "id", in: "path", required: true, schema: z.number(), probeValue: 758 },
      { name: "userid", in: "query", required: false, schema: z.number(), probeValue: 1 },
      { name: "from", in: "query", required: true, schema: z.number(), probeValue: 0 },
      { name: "size", in: "query", required: true, schema: z.number(), probeValue: 2 },
    ],
    responses: {
      "200": {
        description: "Recent topics",
        contentType: "application/json",
        schema: z.array(topicSchema),
      },
      default: {
        description: "API 错误码",
        contentType: "application/json",
        schema: errorCodeSchema,
      },
    },
    auth: "required",
    risk: "read-only",
    verificationStatus: "verified-authenticated",
    sources: ["legacy-openapi", "live-probe"],
  },
  {
    method: "PUT",
    path: "/user/{id}/operation",
    operationId: "putUserIdOperation",
    summary: "Apply or cancel a user punishment",
    tags: ["User", "Moderation"],
    parameters: [{ name: "id", in: "path", required: true, schema: z.number(), probeValue: 758 }],
    requestBody: {
      required: true,
      contentType: "application/json",
      schema: userOperationRequestSchema,
    },
    responses: { "200": { description: "Success" } },
    auth: "required",
    risk: "destructive",
    verificationStatus: "unknown",
    sources: ["legacy-openapi", "live-probe"],
  },
  {
    method: "DELETE",
    path: "/user/{id}/post",
    operationId: "deleteUserIdPost",
    summary: "Delete a user's recent posts",
    tags: ["User", "Moderation"],
    parameters: [
      { name: "id", in: "path", required: true, schema: z.number(), probeValue: 758 },
      { name: "days", in: "query", required: true, schema: z.number() },
    ],
    responses: { "200": { description: "Success" } },
    auth: "required",
    risk: "destructive",
    verificationStatus: "unknown",
    sources: ["legacy-openapi", "live-probe"],
  },
  {
    method: "GET",
    path: "/user/{id}/post",
    operationId: "getUserIdPost",
    summary: "Get a user's recent posts for moderation",
    tags: ["User", "Post", "Moderation"],
    parameters: [
      { name: "id", in: "path", required: true, schema: z.number(), probeValue: 1 },
      { name: "days", in: "query", required: true, schema: z.number(), probeValue: 1 },
      { name: "from", in: "query", required: true, schema: z.number(), probeValue: 0 },
      { name: "size", in: "query", required: true, schema: z.number(), probeValue: 2 },
    ],
    responses: {
      "200": { description: "Legacy moderation response; live schema not verified" },
      "401": {
        description: "Authentication rejected",
        contentType: "application/json",
        schema: errorCodeSchema,
      },
    },
    auth: "required",
    risk: "destructive",
    verificationStatus: "authentication-rejected",
    sources: ["legacy-openapi", "live-probe"],
    description:
      "旧管理页面读取 postInfos 和 count；2026-07-11 使用普通注册用户 token 实测返回空响应体的 401，成功响应结构尚未验证。",
  },
  {
    method: "DELETE",
    path: "/user/{id}/topic",
    operationId: "deleteUserIdTopic",
    summary: "Delete a user's recent topics",
    tags: ["User", "Moderation"],
    parameters: [
      { name: "id", in: "path", required: true, schema: z.number(), probeValue: 758 },
      { name: "days", in: "query", required: true, schema: z.number() },
    ],
    responses: { "200": { description: "Success" } },
    auth: "required",
    risk: "destructive",
    verificationStatus: "unknown",
    sources: ["legacy-openapi", "live-probe"],
  },
]);
