import { z } from "zod";
import { defineOperations } from "./types.ts";
import {
  basicUserSchema,
  errorCodeSchema,
  topicSchema,
  userSchema,
  userOperationRequestSchema,
  userModerationPostPageSchema,
} from "../schemas/index.ts";

export const userOperations = defineOperations([
  {
    method: "GET",
    path: "/user/{id}",
    operationId: "getUserId",
    summary: "按 ID 获取用户资料",
    tags: ["User"],
    parameters: [
      {
        name: "id",
        in: "path",
        required: true,
        schema: z.number().int().positive(),
        description: "用户 ID。",
        probeValue: 1,
      },
    ],
    responses: {
      "200": { description: "用户详细资料", contentType: "application/json", schema: userSchema },
      default: {
        description: "API 错误码",
        contentType: "application/json",
        schema: errorCodeSchema,
      },
    },
    auth: "anonymous",
    risk: "read-only",
    verificationStatus: "verified-anonymous",
    sources: ["legacy-openapi", "live-probe"],
    description: "根据用户 ID 返回用户详细资料。资料隐私设置会影响邮箱、QQ、生日等字段的实际值。",
  },
  {
    method: "GET",
    path: "/user/name/{userName}",
    operationId: "getUserNameUserName",
    summary: "按用户名获取用户资料",
    tags: ["User"],
    parameters: [
      {
        name: "userName",
        in: "path",
        required: true,
        schema: z.string().min(1),
        description: "用户名。",
        probeValue: "shellRain",
      },
    ],
    responses: {
      "200": { description: "用户详细资料", contentType: "application/json", schema: userSchema },
      default: {
        description: "API 错误码",
        contentType: "application/json",
        schema: errorCodeSchema,
      },
    },
    auth: "anonymous",
    risk: "read-only",
    verificationStatus: "verified-anonymous",
    sources: ["legacy-openapi", "live-probe"],
    description: "根据用户名返回用户详细资料。资料隐私设置会影响邮箱、QQ、生日等字段的实际值。",
  },
  {
    method: "GET",
    path: "/user",
    operationId: "getUser",
    summary: "批量获取用户资料",
    tags: ["User"],
    parameters: [
      {
        name: "id",
        in: "query",
        required: true,
        schema: z.array(z.number().int().positive()),
        description: "用户 ID 列表。查询字符串中重复传入 `id` 可一次获取多个用户。",
        probeValue: 1,
      },
    ],
    responses: {
      "200": {
        description: "用户详细资料列表",
        contentType: "application/json",
        schema: z.array(userSchema),
      },
      default: {
        description: "API 错误码",
        contentType: "application/json",
        schema: errorCodeSchema,
      },
    },
    auth: "anonymous",
    risk: "read-only",
    verificationStatus: "verified-anonymous",
    sources: ["legacy-openapi", "live-probe"],
    description: "按照一个或多个用户 ID 批量返回用户详细资料。不存在的用户不会出现在结果中。",
  },
  {
    method: "GET",
    path: "/user/name",
    operationId: "getUserName",
    summary: "按用户名批量获取用户资料",
    tags: ["User"],
    parameters: [
      {
        name: "name",
        in: "query",
        required: true,
        schema: z.array(z.string().min(1)),
        description: "用户名列表。查询字符串中重复传入 `name` 可一次获取多个用户。",
        probeValue: "shellRain",
      },
    ],
    responses: {
      "200": {
        description: "用户详细资料列表",
        contentType: "application/json",
        schema: z.array(userSchema),
      },
      default: {
        description: "API 错误码",
        contentType: "application/json",
        schema: errorCodeSchema,
      },
    },
    auth: "anonymous",
    risk: "read-only",
    verificationStatus: "verified-anonymous",
    sources: ["legacy-openapi", "live-probe"],
    description: "按照一个或多个用户名批量返回用户详细资料。不存在的用户不会出现在结果中。",
  },
  {
    method: "GET",
    path: "/user/basic",
    operationId: "getUserBasic",
    summary: "批量获取用户基础信息",
    tags: ["User"],
    parameters: [
      {
        name: "id",
        in: "query",
        required: true,
        schema: z.array(z.number().int().positive()),
        description: "用户 ID 列表。查询字符串中重复传入 `id` 可一次获取多个用户。",
        probeValue: 1,
      },
    ],
    responses: {
      "200": {
        description: "用户基础信息列表",
        contentType: "application/json",
        schema: z.array(basicUserSchema),
      },
      default: {
        description: "API 错误码",
        contentType: "application/json",
        schema: errorCodeSchema,
      },
    },
    auth: "anonymous",
    risk: "read-only",
    verificationStatus: "verified-anonymous",
    sources: ["legacy-openapi", "live-probe"],
    description: "按照一个或多个用户 ID 批量返回用户 ID、用户名和头像地址。",
  },
  {
    method: "GET",
    path: "/user/basic/{id}",
    operationId: "getUserBasicId",
    summary: "按 ID 获取用户基础信息",
    tags: ["User"],
    parameters: [
      {
        name: "id",
        in: "path",
        required: true,
        schema: z.number().int().positive(),
        description: "用户 ID。",
        probeValue: 1,
      },
    ],
    responses: {
      "200": {
        description: "用户基础信息",
        contentType: "application/json",
        schema: basicUserSchema,
      },
      default: {
        description: "API 错误码",
        contentType: "application/json",
        schema: errorCodeSchema,
      },
    },
    auth: "anonymous",
    risk: "read-only",
    verificationStatus: "verified-anonymous",
    sources: ["legacy-openapi", "live-probe"],
    description: "根据用户 ID 返回用户 ID、用户名和头像地址。",
  },
  {
    method: "GET",
    path: "/user/{id}/recent-topic",
    operationId: "getUserIdRecentTopic",
    summary: "获取用户最近发表的主题",
    tags: ["User", "Topic"],
    parameters: [
      {
        name: "id",
        in: "path",
        required: true,
        schema: z.number().int().positive(),
        description: "用户 ID。",
        probeValue: 1,
      },
      {
        name: "userid",
        in: "query",
        required: false,
        schema: z.number().int().positive(),
        description:
          "兼容旧客户端的用户 ID 参数。路径中的 `id` 已能确定目标用户，当前客户端可以省略此参数。",
      },
      {
        name: "from",
        in: "query",
        required: true,
        schema: z.number().int().nonnegative(),
        description: "从第几条主题开始获取，0 表示第一条。",
        probeValue: 0,
      },
      {
        name: "size",
        in: "query",
        required: true,
        schema: z.number().int().positive(),
        description: "本次最多返回的主题数量。",
        probeValue: 2,
      },
    ],
    responses: {
      "200": {
        description: "用户最近发表的主题列表",
        contentType: "application/json",
        schema: z.array(topicSchema),
      },
      "401": {
        description: "未提供有效身份凭证",
        contentType: "application/json",
        schema: errorCodeSchema,
      },
      default: {
        description: "API 错误码",
        contentType: "application/json",
        schema: errorCodeSchema,
      },
    },
    auth: "required",
    risk: "read-only",
    verificationStatus: "verified-authenticated",
    sources: ["legacy-openapi", "live-probe"],
    description: "分页返回指定用户最近发表的主题。该接口需要登录，但查询其他用户时不要求管理权限。",
  },
  {
    method: "PUT",
    path: "/user/{id}/operation",
    operationId: "putUserIdOperation",
    summary: "执行或解除用户处罚",
    tags: ["User", "Moderation"],
    parameters: [
      {
        name: "id",
        in: "path",
        required: true,
        schema: z.number().int().positive(),
        description: "被处罚或解除处罚的用户 ID。",
        probeValue: 1,
      },
    ],
    requestBody: {
      required: true,
      contentType: "application/json",
      schema: userOperationRequestSchema,
    },
    responses: {
      "200": { description: "处罚操作已处理" },
      default: {
        description: "API 错误码",
        contentType: "application/json",
        schema: errorCodeSchema,
      },
    },
    auth: "required",
    risk: "destructive",
    verificationStatus: "unknown",
    sources: ["legacy-openapi", "live-probe"],
    description:
      "由站点管理员锁定、屏蔽或全站 TP 指定用户，也可解除对应处罚。执行全站 TP 时可指定处罚天数。",
  },
  {
    method: "DELETE",
    path: "/user/{id}/post",
    operationId: "deleteUserIdPost",
    summary: "批量删除用户近期回复",
    tags: ["User", "Moderation"],
    parameters: [
      {
        name: "id",
        in: "path",
        required: true,
        schema: z.number().int().positive(),
        description: "目标用户 ID。",
        probeValue: 1,
      },
      {
        name: "days",
        in: "query",
        required: true,
        schema: z.number().int().positive(),
        description: "删除该用户最近多少天内发表的回复。",
      },
    ],
    responses: {
      "200": {
        description: "已删除的回复数量",
        contentType: "application/json",
        schema: z.number(),
      },
      default: {
        description: "API 错误码",
        contentType: "application/json",
        schema: errorCodeSchema,
      },
    },
    auth: "required",
    risk: "destructive",
    verificationStatus: "unknown",
    sources: ["legacy-openapi", "live-probe"],
    description: "由站点管理员批量删除指定用户在给定天数内发表的回复。",
  },
  {
    method: "GET",
    path: "/user/{id}/post",
    operationId: "getUserIdPost",
    summary: "查询用户近期发言",
    tags: ["User", "Post", "Moderation"],
    parameters: [
      {
        name: "id",
        in: "path",
        required: true,
        schema: z.number().int().positive(),
        description: "目标用户 ID。",
        probeValue: 1,
      },
      {
        name: "days",
        in: "query",
        required: true,
        schema: z.number().int().positive(),
        description: "查询该用户最近多少天内发表的内容。",
        probeValue: 1,
      },
      {
        name: "from",
        in: "query",
        required: true,
        schema: z.number().int().nonnegative(),
        description: "从第几条发言开始获取，0 表示第一条。",
        probeValue: 0,
      },
      {
        name: "size",
        in: "query",
        required: true,
        schema: z.number().int().positive(),
        description: "本次最多返回的发言数量。",
        probeValue: 2,
      },
    ],
    responses: {
      "200": {
        description: "用户近期发言及符合条件的总数",
        contentType: "application/json",
        schema: userModerationPostPageSchema,
      },
      "401": {
        description: "未提供有效身份凭证",
        contentType: "application/json",
        schema: errorCodeSchema,
      },
      "403": {
        description: "当前用户没有站点管理权限",
        contentType: "application/json",
        schema: errorCodeSchema,
      },
      default: {
        description: "API 错误码",
        contentType: "application/json",
        schema: errorCodeSchema,
      },
    },
    auth: "required",
    risk: "read-only",
    verificationStatus: "permission-denied",
    sources: ["legacy-openapi", "live-probe"],
    description: "供站点管理员分页查看指定用户在给定天数内发表的主题正文和回复。",
  },
  {
    method: "DELETE",
    path: "/user/{id}/topic",
    operationId: "deleteUserIdTopic",
    summary: "批量删除用户近期主题",
    tags: ["User", "Moderation"],
    parameters: [
      {
        name: "id",
        in: "path",
        required: true,
        schema: z.number().int().positive(),
        description: "目标用户 ID。",
        probeValue: 1,
      },
      {
        name: "days",
        in: "query",
        required: true,
        schema: z.number().int().positive(),
        description: "删除该用户最近多少天内发表的主题。",
      },
    ],
    responses: {
      "200": {
        description: "已删除的主题数量",
        contentType: "application/json",
        schema: z.number(),
      },
      default: {
        description: "API 错误码",
        contentType: "application/json",
        schema: errorCodeSchema,
      },
    },
    auth: "required",
    risk: "destructive",
    verificationStatus: "unknown",
    sources: ["legacy-openapi", "live-probe"],
    description: "由站点管理员批量删除指定用户在给定天数内发表的主题。",
  },
]);
